"""remove id supply_stats table

Revision ID: 06181d27030b
Revises: 87dfcbe418be
Create Date: 2017-07-22 23:29:13.181166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06181d27030b'
down_revision = '87dfcbe418be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'supply_stats', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supply_stats', type_='foreignkey')
    # ### end Alembic commands ###
