"""add asset_ids product_contents

Revision ID: 066061b528d7
Revises: 8e3808edf29e
Create Date: 2018-03-20 10:29:02.502934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066061b528d7'
down_revision = '8e3808edf29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_contents', sa.Column('asset_ids', sa.String(length=200), nullable=True))
    op.drop_index('ix_product_statistics_master_uid', table_name='product_statistics')
    op.create_index(op.f('ix_product_statistics_master_uid'), 'product_statistics', ['master_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_statistics_master_uid'), table_name='product_statistics')
    op.create_index('ix_product_statistics_master_uid', 'product_statistics', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    op.drop_column('product_contents', 'asset_ids')
    # ### end Alembic commands ###
