"""add master_uid for role table

Revision ID: 0787afd55040
Revises: f43124864055
Create Date: 2017-07-03 01:52:53.436767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0787afd55040'
down_revision = 'f43124864055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.drop_index('name', table_name='roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'roles', ['name'], unique=True)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
