"""add price product table

Revision ID: 08aaff3cbdeb
Revises: e7993bbd0958
Create Date: 2018-03-01 22:50:07.750295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08aaff3cbdeb'
down_revision = 'e7993bbd0958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('sticked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sticked')
    op.drop_column('products', 'price')
    op.drop_column('product_skus', 'price')
    # ### end Alembic commands ###
