"""modify image_id banner

Revision ID: 0bec54f0b51e
Revises: fbb61dfd3ab5
Create Date: 2018-01-02 14:16:25.126321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bec54f0b51e'
down_revision = 'fbb61dfd3ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_images', sa.Column('image_id', sa.Integer(), nullable=True))
    op.drop_column('banner_images', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_images', sa.Column('image', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('banner_images', 'image_id')
    # ### end Alembic commands ###
