"""add product distribute table

Revision ID: 0c73cfddb3fa
Revises: 6aa621543cb2
Create Date: 2018-04-20 11:23:51.782152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c73cfddb3fa'
down_revision = '6aa621543cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_distribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_serial_no', sa.String(length=12), nullable=False),
    sa.Column('product_sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.Column('distribute_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('suggested_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_distribution_created_at'), 'product_distribution', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_distribution_master_uid'), 'product_distribution', ['master_uid'], unique=False)
    op.create_index(op.f('ix_product_distribution_product_serial_no'), 'product_distribution', ['product_serial_no'], unique=False)
    op.create_index(op.f('ix_product_distribution_product_sku_id'), 'product_distribution', ['product_sku_id'], unique=False)
    op.create_index(op.f('ix_product_distribution_sku_serial_no'), 'product_distribution', ['sku_serial_no'], unique=False)
    op.add_column('orders', sa.Column('is_distributed', sa.Boolean(), nullable=True))
    op.add_column('product_contents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('distributer_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_distributed', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('sale_count', sa.Integer(), nullable=True))
    op.add_column('store_products', sa.Column('is_distributed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_products', 'is_distributed')
    op.drop_column('products', 'sale_count')
    op.drop_column('products', 'is_distributed')
    op.drop_column('products', 'distributer_count')
    op.drop_column('product_contents', 'description')
    op.drop_column('orders', 'is_distributed')
    op.drop_index(op.f('ix_product_distribution_sku_serial_no'), table_name='product_distribution')
    op.drop_index(op.f('ix_product_distribution_product_sku_id'), table_name='product_distribution')
    op.drop_index(op.f('ix_product_distribution_product_serial_no'), table_name='product_distribution')
    op.drop_index(op.f('ix_product_distribution_master_uid'), table_name='product_distribution')
    op.drop_index(op.f('ix_product_distribution_created_at'), table_name='product_distribution')
    op.drop_table('product_distribution')
    # ### end Alembic commands ###
