"""add express_at for order table

Revision ID: 0da99b8e42d0
Revises: 9e6c6903ddad
Create Date: 2017-07-10 00:28:09.158272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da99b8e42d0'
down_revision = '9e6c6903ddad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('express_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'express_at')
    # ### end Alembic commands ###
