"""update statistics

Revision ID: 102b83238e21
Revises: 9b7c8e60febc
Create Date: 2017-12-22 15:43:36.124014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102b83238e21'
down_revision = '9b7c8e60febc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'day_sku_statistics', ['store_id', 'sku_id', 'time'])
    op.create_unique_constraint(None, 'product_statistics', ['store_id', 'sku_id', 'time', 'time_type'])
    op.create_unique_constraint(None, 'store_statistics', ['store_id', 'type', 'time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_statistics', type_='unique')
    op.drop_constraint(None, 'product_statistics', type_='unique')
    op.drop_constraint(None, 'day_sku_statistics', type_='unique')
    # ### end Alembic commands ###
