"""update current_count,presale_count product_stock table

Revision ID: 107dbbb75873
Revises: 5e4e33912d51
Create Date: 2017-06-28 16:53:17.669795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107dbbb75873'
down_revision = '5e4e33912d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_stocks', sa.Column('current_count', sa.Integer(), nullable=True))
    op.add_column('product_stocks', sa.Column('presale_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_stocks', 'presale_count')
    op.drop_column('product_stocks', 'current_count')
    # ### end Alembic commands ###
