"""add store_distribute_packets

Revision ID: 108d73a06aa6
Revises: c5db383454c5
Create Date: 2018-04-11 23:03:18.044880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108d73a06aa6'
down_revision = 'c5db383454c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_distribute_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('product_packet_id', sa.Integer(), nullable=True),
    sa.Column('discount_templet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_packet_id'], ['product_packets.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_product_statistics_master_uid', table_name='product_statistics')
    op.create_index(op.f('ix_product_statistics_master_uid'), 'product_statistics', ['master_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_statistics_master_uid'), table_name='product_statistics')
    op.create_index('ix_product_statistics_master_uid', 'product_statistics', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    op.drop_table('store_distribute_packets')
    # ### end Alembic commands ###
