"""add suggested_max_price table

Revision ID: 131f56c3afc6
Revises: 0c73cfddb3fa
Create Date: 2018-04-22 00:14:43.567917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '131f56c3afc6'
down_revision = '0c73cfddb3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_distribution', sa.Column('suggested_max_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('product_distribution', sa.Column('suggested_min_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('product_distribution', 'suggested_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_distribution', sa.Column('suggested_price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('product_distribution', 'suggested_min_price')
    op.drop_column('product_distribution', 'suggested_max_price')
    # ### end Alembic commands ###
