"""add total_count for product_packet

Revision ID: 1407bf4314ee
Revises: 2bff8480095b
Create Date: 2017-12-07 18:12:37.746705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1407bf4314ee'
down_revision = '2bff8480095b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_packets', sa.Column('total_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_packets', 'total_count')
    # ### end Alembic commands ###
