"""modify master_uid currency table

Revision ID: 15663395a43d
Revises: 6438918cc6fa
Create Date: 2017-08-14 01:33:38.337937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15663395a43d'
down_revision = '6438918cc6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('master_uid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'master_uid')
    # ### end Alembic commands ###
