"""add region_id for product table

Revision ID: 15bf3259922d
Revises: 15663395a43d
Create Date: 2017-08-20 23:43:48.158805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bf3259922d'
down_revision = '15663395a43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('id_code', sa.String(length=16), nullable=True))
    op.add_column('product_skus', sa.Column('region_id', sa.SmallInteger(), nullable=True))
    op.add_column('product_skus', sa.Column('s_color', sa.String(length=32), nullable=True))
    op.add_column('products', sa.Column('region_id', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'region_id')
    op.drop_column('product_skus', 's_color')
    op.drop_column('product_skus', 'region_id')
    op.drop_column('product_skus', 'id_code')
    # ### end Alembic commands ###
