"""modify field type for order/order_item table

Revision ID: 15cb1311e71d
Revises: 6e90d9978fc0
Create Date: 2017-07-01 15:30:00.809836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15cb1311e71d'
down_revision = '6e90d9978fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_serial_no', table_name='orders')
    op.drop_column('orders', 'serial_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('serial_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_index('ix_orders_serial_no', 'orders', ['serial_no'], unique=True)
    # ### end Alembic commands ###
