"""debug serial_no product table

Revision ID: 17677fb0670f
Revises: 886f408d8ffd
Create Date: 2017-08-09 01:13:03.518228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17677fb0670f'
down_revision = '886f408d8ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_skus_serial_no', table_name='product_skus')
    op.drop_column('product_skus', 'serial_no')
    op.drop_index('ix_products_serial_no', table_name='products')
    op.drop_column('products', 'serial_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('serial_no', mysql.VARCHAR(length=12), server_default=sa.text("''"), nullable=False))
    op.create_index('ix_products_serial_no', 'products', ['serial_no'], unique=True)
    op.add_column('product_skus', sa.Column('serial_no', mysql.VARCHAR(length=12), server_default=sa.text("''"), nullable=False))
    op.create_index('ix_product_skus_serial_no', 'product_skus', ['serial_no'], unique=True)
    # ### end Alembic commands ###
