"""add place table

Revision ID: 19fc4046be2c
Revises: 5815c40d5176
Create Date: 2017-12-28 17:26:28.109928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19fc4046be2c'
down_revision = '5815c40d5176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expired_at', sa.Integer(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('product_rid', sa.String(length=12), nullable=True),
    sa.Column('xname', sa.String(length=8), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('get_at', sa.Integer(), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('order_rid', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('layer', sa.SmallInteger(), nullable=True),
    sa.Column('sort_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('addresses', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('addresses', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('addresses', sa.Column('province_id', sa.Integer(), nullable=True))
    op.add_column('addresses', sa.Column('town', sa.String(length=50), nullable=True))
    op.add_column('addresses', sa.Column('town_id', sa.Integer(), nullable=True))
    op.drop_column('addresses', 'country')
    op.drop_index('ix_product_statistics_master_uid', table_name='product_statistics')
    op.create_index(op.f('ix_product_statistics_master_uid'), 'product_statistics', ['master_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_statistics_master_uid'), table_name='product_statistics')
    op.create_index('ix_product_statistics_master_uid', 'product_statistics', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    op.add_column('addresses', sa.Column('country', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('addresses', 'town_id')
    op.drop_column('addresses', 'town')
    op.drop_column('addresses', 'province_id')
    op.drop_column('addresses', 'mobile')
    op.drop_column('addresses', 'country_id')
    op.drop_table('places')
    op.drop_table('invitations')
    op.drop_table('bonus')
    # ### end Alembic commands ###
