"""add customer_code orders table

Revision ID: 1aee3df335f8
Revises: 5773d76bafbd
Create Date: 2018-04-03 01:19:25.470344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aee3df335f8'
down_revision = '5773d76bafbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_code', sa.String(length=20), nullable=True))
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('orders', 'customer_code')
    # ### end Alembic commands ###
