"""update category unique index

Revision ID: 1b581e8043ab
Revises: 7f3048b98a93
Create Date: 2017-07-20 11:14:07.539824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b581e8043ab'
down_revision = '7f3048b98a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_master_uid_pid', 'categories', ['master_uid', 'pid'], unique=False)
    op.create_unique_constraint('uix_master_uid_name', 'categories', ['master_uid', 'name'])
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=True)
    op.drop_constraint('uix_master_uid_name', 'categories', type_='unique')
    op.drop_index('ix_master_uid_pid', table_name='categories')
    # ### end Alembic commands ###
