"""add customer_distribute_packets

Revision ID: 1d1e162f5d6c
Revises: 4507ccb4450f
Create Date: 2017-12-09 16:47:51.598014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1e162f5d6c'
down_revision = '4507ccb4450f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_distribute_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_packet_id', sa.Integer(), nullable=True),
    sa.Column('discount_templet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['discount_templet_id'], ['discount_templets.id'], ),
    sa.ForeignKeyConstraint(['product_packet_id'], ['product_packets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_distribute_packets')
    # ### end Alembic commands ###
