"""modify wishlist table

Revision ID: 211609027f83
Revises: 585ce54fe8f5
Create Date: 2018-03-06 22:23:13.508124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '211609027f83'
down_revision = '585ce54fe8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('product_rid', sa.String(length=12), nullable=False))
    op.drop_column('wishlist', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('wishlist', 'product_rid')
    # ### end Alembic commands ###
