"""update brand table

Revision ID: 231e32bfdae3
Revises: 7bb2a8707fb6
Create Date: 2017-11-28 13:42:49.028291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '231e32bfdae3'
down_revision = '7bb2a8707fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('banner_id', sa.Integer(), nullable=True))
    op.add_column('brands', sa.Column('sn', sa.String(length=9), nullable=True))
    op.create_index(op.f('ix_brands_sn'), 'brands', ['sn'], unique=True)
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('published_at', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.alter_column('users', 'sn',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.create_index(op.f('ix_users_sn'), 'users', ['sn'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sn'), table_name='users')
    op.alter_column('users', 'sn',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'published_at')
    op.drop_column('products', 'brand_id')
    op.drop_index(op.f('ix_brands_sn'), table_name='brands')
    op.drop_column('brands', 'sn')
    op.drop_column('brands', 'banner_id')
    # ### end Alembic commands ###
