"""remove brand_id for product table

Revision ID: 239b23e3fc95
Revises: b9effe1f5f87
Create Date: 2017-06-15 23:53:40.134650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '239b23e3fc95'
down_revision = 'b9effe1f5f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_ibfk_3', 'products', type_='foreignkey')
    op.drop_column('products', 'brand_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('products_ibfk_3', 'products', 'brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###
