"""add client

Revision ID: 2a5c0b59f0f9
Revises: cba4bc28cc67
Create Date: 2017-11-15 22:40:26.313220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5c0b59f0f9'
down_revision = 'cba4bc28cc67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('app_key', sa.String(length=20), nullable=False),
    sa.Column('app_secret', sa.String(length=40), nullable=False),
    sa.Column('limit_times', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=140), nullable=True),
    sa.Column('white_list', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_key'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
