"""update product brand_id table

Revision ID: 2a80487c151d
Revises: 55c4721d71cd
Create Date: 2017-06-14 16:14:02.853011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a80487c151d'
down_revision = '55c4721d71cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'brand_id')
    # ### end Alembic commands ###
