"""add id_type for user

Revision ID: 2b5075cda424
Revises: 638c284c1266
Create Date: 2017-11-22 11:09:06.563976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5075cda424'
down_revision = '638c284c1266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pay_mode', sa.SmallInteger(), nullable=True),
    sa.Column('sale_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_services_name'), 'app_services', ['name'], unique=False)
    op.create_index(op.f('ix_app_services_serial_no'), 'app_services', ['serial_no'], unique=True)
    op.create_table('service_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pay_mode', sa.SmallInteger(), nullable=True),
    sa.Column('discount_money', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ordered_at', sa.Integer(), nullable=True),
    sa.Column('ordered_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['app_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribe_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('ordered_at', sa.Integer(), nullable=True),
    sa.Column('expired_at', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['app_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('id_type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id_type')
    op.drop_table('subscribe_services')
    op.drop_table('service_transactions')
    op.drop_index(op.f('ix_app_services_serial_no'), table_name='app_services')
    op.drop_index(op.f('ix_app_services_name'), table_name='app_services')
    op.drop_table('app_services')
    # ### end Alembic commands ###
