"""add serial_no banner

Revision ID: 2bf47066ddd7
Revises: 3d15e9c3d82f
Create Date: 2018-01-02 15:19:25.253128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf47066ddd7'
down_revision = '3d15e9c3d82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('serial_no', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_banners_serial_no'), 'banners', ['serial_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banners_serial_no'), table_name='banners')
    op.drop_column('banners', 'serial_no')
    # ### end Alembic commands ###
