"""add product_packet table

Revision ID: 2bff8480095b
Revises: a48df7bf58fe
Create Date: 2017-12-07 16:00:08.839569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bff8480095b'
down_revision = 'a48df7bf58fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_templets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('default_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount_templet_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('discount_templet_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discount_templet_id'], ['discount_templets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('discount_templet_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discount_templet_id'], ['discount_templets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_packets',
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_packet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_packet_id'], ['product_packets.id'], )
    )
    op.create_table('packet_products',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_packet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_packet_id'], ['product_packets.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packet_products')
    op.drop_table('customer_packets')
    op.drop_table('product_packets')
    op.drop_table('discount_templet_items')
    op.drop_table('discount_templets')
    # ### end Alembic commands ###
