"""add sku_serial_no for order_item table

Revision ID: 2e87c15d0fdd
Revises: 0da99b8e42d0
Create Date: 2017-07-10 16:52:17.150797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e87c15d0fdd'
down_revision = '0da99b8e42d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_sku_serial_no', table_name='order_items')
    op.drop_column('order_items', 'sku_serial_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('sku_serial_no', mysql.VARCHAR(length=12), server_default=sa.text("''"), nullable=False))
    op.create_index('ix_order_items_sku_serial_no', 'order_items', ['sku_serial_no'], unique=False)
    # ### end Alembic commands ###
