"""add opreator_id for store table

Revision ID: 324c552f3a44
Revises: ef933845b398
Create Date: 2017-08-26 22:01:20.110011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324c552f3a44'
down_revision = 'ef933845b398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('operator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stores', 'users', ['operator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'operator_id')
    # ### end Alembic commands ###
