"""add cover mini_app table

Revision ID: 3326864aabca
Revises: 066061b528d7
Create Date: 2018-03-28 00:24:09.367221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3326864aabca'
down_revision = '066061b528d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_mini_apps', sa.Column('cover_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wx_mini_apps', 'cover_id')
    # ### end Alembic commands ###
