"""add country table

Revision ID: 338dc5c498b1
Revises: fea57f68a4b0
Create Date: 2017-07-11 11:18:40.376108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338dc5c498b1'
down_revision = 'fea57f68a4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('countries', sa.Column('updated_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'updated_at')
    op.drop_column('countries', 'created_at')
    # ### end Alembic commands ###
