"""add buyer_area to orders

Revision ID: 3841d5a8e12c
Revises: ffa9899bfd2c
Create Date: 2017-10-18 17:42:56.741281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3841d5a8e12c'
down_revision = 'ffa9899bfd2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('buyer_area', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'buyer_area')
    # ### end Alembic commands ###
