"""add outside_serial_no for product_sku table

Revision ID: 39bf392ad9c0
Revises: ce2e7c691bd6
Create Date: 2017-07-16 18:01:49.198370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bf392ad9c0'
down_revision = 'ce2e7c691bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('outside_serial_no', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_product_skus_outside_serial_no'), 'product_skus', ['outside_serial_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_skus_outside_serial_no'), table_name='product_skus')
    op.drop_column('product_skus', 'outside_serial_no')
    # ### end Alembic commands ###
