"""remove language_id banner

Revision ID: 3d15e9c3d82f
Revises: 0bec54f0b51e
Create Date: 2018-01-02 15:02:05.574112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d15e9c3d82f'
down_revision = '0bec54f0b51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('banner_images_ibfk_2', 'banner_images', type_='foreignkey')
    op.drop_column('banner_images', 'language_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_images', sa.Column('language_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('banner_images_ibfk_2', 'banner_images', 'languages', ['language_id'], ['id'])
    # ### end Alembic commands ###
