"""add  day sku statistics

Revision ID: 3dcd010f1d46
Revises: d45291bf67f9
Create Date: 2017-12-18 16:34:38.014079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3dcd010f1d46'
down_revision = 'd45291bf67f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_sku_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_sku_statistics_category_id'), 'day_sku_statistics', ['category_id'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_master_uid'), 'day_sku_statistics', ['master_uid'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_product_id'), 'day_sku_statistics', ['product_id'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_sku_id'), 'day_sku_statistics', ['sku_id'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_sku_serial_no'), 'day_sku_statistics', ['sku_serial_no'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_store_id'), 'day_sku_statistics', ['store_id'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_supplier_id'), 'day_sku_statistics', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_time'), 'day_sku_statistics', ['time'], unique=False)
    op.alter_column('sales_log_statistics', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index(op.f('ix_sales_log_statistics_product_id'), 'sales_log_statistics', ['product_id'], unique=False)
    op.create_foreign_key(None, 'sales_log_statistics', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_log_statistics', type_='foreignkey')
    op.drop_index(op.f('ix_sales_log_statistics_product_id'), table_name='sales_log_statistics')
    op.alter_column('sales_log_statistics', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    op.drop_index(op.f('ix_day_sku_statistics_time'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_supplier_id'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_store_id'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_sku_serial_no'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_sku_id'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_product_id'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_master_uid'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_category_id'), table_name='day_sku_statistics')
    op.drop_table('day_sku_statistics')
    # ### end Alembic commands ###
