"""add express info for purchase table

Revision ID: 3e4fe2d9a72b
Revises: 32d61671685f
Create Date: 2017-07-09 22:12:03.699108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4fe2d9a72b'
down_revision = '32d61671685f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('express_name', sa.String(length=30), nullable=True))
    op.add_column('purchases', sa.Column('express_no', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'express_no')
    op.drop_column('purchases', 'express_name')
    # ### end Alembic commands ###
