"""add in_quantity for purchase table

Revision ID: 44d2e1429a2c
Revises: 5b82b7b6d4a9
Create Date: 2017-06-27 17:13:24.790557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d2e1429a2c'
down_revision = '5b82b7b6d4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('in_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'in_quantity')
    # ### end Alembic commands ###
