"""remove customer_packets

Revision ID: 4507ccb4450f
Revises: 4fac9e2df059
Create Date: 2017-12-09 16:43:10.873017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4507ccb4450f'
down_revision = '4fac9e2df059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_packets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_packets',
    sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('product_packet_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('discount_templet_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='customer_packets_ibfk_1'),
    sa.ForeignKeyConstraint(['discount_templet_id'], ['discount_templets.id'], name='customer_packets_ibfk_3'),
    sa.ForeignKeyConstraint(['product_packet_id'], ['product_packets.id'], name='customer_packets_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
