"""modify app_id auth_app_id wx_mini_apps table

Revision ID: 47f6774e905c
Revises: af2cb945b548
Create Date: 2018-02-23 15:49:13.368933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47f6774e905c'
down_revision = 'af2cb945b548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_mini_apps', sa.Column('auth_app_id', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_wx_mini_apps_auth_app_id'), 'wx_mini_apps', ['auth_app_id'], unique=False)
    op.drop_index('ix_wx_mini_apps_app_id', table_name='wx_mini_apps')
    op.drop_column('wx_mini_apps', 'app_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_mini_apps', sa.Column('app_id', mysql.VARCHAR(length=20), nullable=False))
    op.create_index('ix_wx_mini_apps_app_id', 'wx_mini_apps', ['app_id'], unique=False)
    op.drop_index(op.f('ix_wx_mini_apps_auth_app_id'), table_name='wx_mini_apps')
    op.drop_column('wx_mini_apps', 'auth_app_id')
    # ### end Alembic commands ###
