"""add site table

Revision ID: 4ae6b6a1e223
Revises: 228245e23a1e
Create Date: 2017-07-02 15:53:32.242613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae6b6a1e223'
down_revision = '228245e23a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('sites', sa.Column('update_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'update_at')
    op.drop_column('sites', 'created_at')
    # ### end Alembic commands ###
