"""add order_item table

Revision ID: 4fa22c916834
Revises: bbf70cd44a63
Create Date: 2017-06-22 19:34:50.782362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fa22c916834'
down_revision = 'bbf70cd44a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('outside_target_id', sa.String(length=32), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('pay_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('freight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('express_id', sa.Integer(), nullable=True),
    sa.Column('express_no', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('invoice_type', sa.SmallInteger(), nullable=True),
    sa.Column('buyer_name', sa.String(length=50), nullable=False),
    sa.Column('buyer_tel', sa.String(length=20), nullable=True),
    sa.Column('buyer_phone', sa.String(length=20), nullable=True),
    sa.Column('buyer_zipcode', sa.String(length=16), nullable=True),
    sa.Column('buyer_address', sa.String(length=200), nullable=True),
    sa.Column('buyer_country', sa.String(length=50), nullable=True),
    sa.Column('buyer_province', sa.String(length=50), nullable=True),
    sa.Column('buyer_city', sa.String(length=50), nullable=True),
    sa.Column('buyer_remark', sa.String(length=250), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('suspend', sa.Boolean(), nullable=True),
    sa.Column('expired_time', sa.Integer(), nullable=True),
    sa.Column('from_client', sa.SmallInteger(), nullable=True),
    sa.Column('affiliate_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.Integer(), nullable=True),
    sa.Column('payed_at', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['express_id'], ['expresses.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_buyer_name'), 'orders', ['buyer_name'], unique=False)
    op.create_index(op.f('ix_orders_buyer_phone'), 'orders', ['buyer_phone'], unique=False)
    op.create_index(op.f('ix_orders_buyer_tel'), 'orders', ['buyer_tel'], unique=False)
    op.create_index(op.f('ix_orders_master_uid'), 'orders', ['master_uid'], unique=False)
    op.create_index(op.f('ix_orders_outside_target_id'), 'orders', ['outside_target_id'], unique=False)
    op.create_index(op.f('ix_orders_serial_no'), 'orders', ['serial_no'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('deal_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('serial_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('master_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('outside_target_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pay_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('freight', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('express_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('express_no', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('invoice_type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('buyer_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('buyer_tel', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('buyer_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('buyer_zipcode', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('buyer_address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('buyer_country', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('buyer_province', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('buyer_city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('buyer_remark', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('suspend', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('expired_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('from_client', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('affiliate_code', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('created_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('verified_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('payed_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('closed_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['express_id'], ['expresses.id'], name='order_ibfk_1'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='order_ibfk_2'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='order_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_serial_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_outside_target_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_master_uid'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_tel'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_phone'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_name'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
