"""add discount templet id for customer_packets

Revision ID: 4fac9e2df059
Revises: 8378e31b4908
Create Date: 2017-12-09 16:34:17.639324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fac9e2df059'
down_revision = '8378e31b4908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_packets', sa.Column('discount_templet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer_packets', 'discount_templets', ['discount_templet_id'], ['id'])
    op.drop_constraint('product_packets_ibfk_1', 'product_packets', type_='foreignkey')
    op.drop_column('product_packets', 'discount_templet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_packets', sa.Column('discount_templet_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('product_packets_ibfk_1', 'product_packets', 'discount_templets', ['discount_templet_id'], ['id'])
    op.drop_constraint(None, 'customer_packets', type_='foreignkey')
    op.drop_column('customer_packets', 'discount_templet_id')
    # ### end Alembic commands ###
