"""add is_setting user table

Revision ID: 526f47c882c7
Revises: 4ae6b6a1e223
Create Date: 2017-07-02 16:04:12.121632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526f47c882c7'
down_revision = '4ae6b6a1e223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_setting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_setting')
    # ### end Alembic commands ###
