"""add product/sku/supplier/brand/category table

Revision ID: 54c4bfbda7dc
Revises: eb0bd00a8499
Create Date: 2017-06-14 13:25:50.259424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c4bfbda7dc'
down_revision = 'eb0bd00a8499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('features', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_created_at'), 'brands', ['created_at'], unique=False)
    op.create_index(op.f('ix_brands_master_uid'), 'brands', ['master_uid'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_master_uid'), 'categories', ['master_uid'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('time_limit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_suppliers_master_uid'), 'suppliers', ['master_uid'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('id_code', sa.String(length=16), nullable=True),
    sa.Column('cost_price', sa.Float(precision=15, asdecimal=4), nullable=True),
    sa.Column('sale_price', sa.Float(precision=15, asdecimal=4), nullable=True),
    sa.Column('s_weight', sa.Float(precision=15, asdecimal=4), nullable=True),
    sa.Column('s_length', sa.Float(precision=15, asdecimal=4), nullable=True),
    sa.Column('s_width', sa.Float(precision=15, asdecimal=4), nullable=True),
    sa.Column('s_height', sa.Float(precision=15, asdecimal=4), nullable=True),
    sa.Column('from_url', sa.String(length=255), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cover_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_master_uid'), 'products', ['master_uid'], unique=False)
    op.create_index(op.f('ix_products_serial_no'), 'products', ['serial_no'], unique=True)
    op.create_table('categories_products',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    op.create_table('customs_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('dangerous_goods', sa.String(length=1), nullable=True),
    sa.Column('local_name', sa.String(length=100), nullable=False),
    sa.Column('en_name', sa.String(length=100), nullable=False),
    sa.Column('s_weight', sa.Float(precision=15, asdecimal=4), nullable=True),
    sa.Column('amount', sa.Float(precision=15, asdecimal=4), nullable=True),
    sa.Column('customs_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customs_declarations_created_at'), 'customs_declarations', ['created_at'], unique=False)
    op.create_table('product_skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('s_weight', sa.Float(precision=15, asdecimal=4), nullable=True),
    sa.Column('cost_price', sa.Float(precision=15, asdecimal=4), nullable=True),
    sa.Column('sale_price', sa.Float(precision=15, asdecimal=4), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['cover_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_skus_serial_no'), 'product_skus', ['serial_no'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_skus_serial_no'), table_name='product_skus')
    op.drop_table('product_skus')
    op.drop_index(op.f('ix_customs_declarations_created_at'), table_name='customs_declarations')
    op.drop_table('customs_declarations')
    op.drop_table('categories_products')
    op.drop_index(op.f('ix_products_serial_no'), table_name='products')
    op.drop_index(op.f('ix_products_master_uid'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_suppliers_master_uid'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_master_uid'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_master_uid'), table_name='brands')
    op.drop_index(op.f('ix_brands_created_at'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
