"""add edition user table

Revision ID: 56ea592e0512
Revises: dd01791162ea
Create Date: 2018-03-13 09:40:32.269331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56ea592e0512'
down_revision = 'dd01791162ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('brands_ibfk_1', 'brands', type_='foreignkey')
    op.add_column('product_skus', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('total_stock', sa.Integer(), nullable=True))
    op.drop_constraint('products_ibfk_4', 'products', type_='foreignkey')
    op.drop_constraint('products_ibfk_3', 'products', type_='foreignkey')
    op.drop_constraint('products_ibfk_1', 'products', type_='foreignkey')
    op.drop_column('products', 'currency_id')
    op.add_column('users', sa.Column('edition', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'edition')
    op.add_column('products', sa.Column('currency_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('products_ibfk_1', 'products', 'brands', ['brand_id'], ['id'])
    op.create_foreign_key('products_ibfk_3', 'products', 'currencies', ['currency_id'], ['id'])
    op.create_foreign_key('products_ibfk_4', 'products', 'suppliers', ['supplier_id'], ['id'])
    op.drop_column('products', 'total_stock')
    op.drop_column('product_skus', 'stock_quantity')
    op.create_foreign_key('brands_ibfk_1', 'brands', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###
