"""add product_content table

Revision ID: 5815c40d5176
Revises: eb4cc5c550a5
Create Date: 2017-12-28 11:35:56.534908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5815c40d5176'
down_revision = 'eb4cc5c550a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_contents_created_at'), 'product_contents', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_contents_master_uid'), 'product_contents', ['master_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_contents_master_uid'), table_name='product_contents')
    op.drop_index(op.f('ix_product_contents_created_at'), table_name='product_contents')
    op.drop_table('product_contents')
    # ### end Alembic commands ###
