"""add currency_id for warehouse

Revision ID: 5ae6e612025a
Revises: dc0f6246eced
Create Date: 2017-09-02 09:04:54.735059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae6e612025a'
down_revision = 'dc0f6246eced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'warehouses', 'currencies', ['currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'currency_id')
    # ### end Alembic commands ###
