"""update product stock table

Revision ID: 5b82b7b6d4a9
Revises: de21a93bf577
Create Date: 2017-06-27 15:18:50.079694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b82b7b6d4a9'
down_revision = 'de21a93bf577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_stocks', sa.Column('defective_count', sa.Integer(), nullable=True))
    op.add_column('warehouse_in_list', sa.Column('warehouse_shelve_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'warehouse_in_list', 'warehouse_shelves', ['warehouse_shelve_id'], ['id'])
    op.drop_column('warehouse_in_list', 'in_quantity')
    op.add_column('warehouse_in_products', sa.Column('new_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('warehouse_in_products', sa.Column('new_stock', sa.Integer(), nullable=True))
    op.add_column('warehouse_in_products', sa.Column('ori_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('warehouse_in_products', sa.Column('ori_stock', sa.Integer(), nullable=True))
    op.drop_column('warehouse_in_products', 'total_quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_in_products', sa.Column('total_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('warehouse_in_products', 'ori_stock')
    op.drop_column('warehouse_in_products', 'ori_price')
    op.drop_column('warehouse_in_products', 'new_stock')
    op.drop_column('warehouse_in_products', 'new_price')
    op.add_column('warehouse_in_list', sa.Column('in_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'warehouse_in_list', type_='foreignkey')
    op.drop_column('warehouse_in_list', 'warehouse_shelve_id')
    op.drop_column('product_stocks', 'defective_count')
    # ### end Alembic commands ###
