"""update warehouse_shelve_id stock history table

Revision ID: 5e4e33912d51
Revises: deb58845fbb5
Create Date: 2017-06-28 13:30:19.174826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4e33912d51'
down_revision = 'deb58845fbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_stock_history', sa.Column('warehouse_shelve_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'warehouse_stock_history', 'warehouse_shelves', ['warehouse_shelve_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse_stock_history', type_='foreignkey')
    op.drop_column('warehouse_stock_history', 'warehouse_shelve_id')
    # ### end Alembic commands ###
