"""add s_model for product_sku table

Revision ID: 5eadfefeebb0
Revises: da5734e95149
Create Date: 2017-06-20 23:46:22.763003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eadfefeebb0'
down_revision = 'da5734e95149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('s_model', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_skus', 's_model')
    # ### end Alembic commands ###
