"""update country table

Revision ID: 5f53fd101465
Revises: 19fc4046be2c
Create Date: 2017-12-28 18:44:45.742005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f53fd101465'
down_revision = '19fc4046be2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('name', sa.String(length=128), nullable=False))
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=False)
    op.drop_index('ix_countries_cn_name', table_name='countries')
    op.drop_column('countries', 'cn_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('cn_name', mysql.VARCHAR(length=128), nullable=False))
    op.create_index('ix_countries_cn_name', 'countries', ['cn_name'], unique=False)
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_column('countries', 'name')
    # ### end Alembic commands ###
