"""modify currency_id site table

Revision ID: 6438918cc6fa
Revises: 5754e30ca6c2
Create Date: 2017-08-14 01:06:03.876936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6438918cc6fa'
down_revision = '5754e30ca6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sites', 'currencies', ['currency_id'], ['id'])
    op.drop_column('sites', 'currency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('currency', mysql.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_column('sites', 'currency_id')
    # ### end Alembic commands ###
