"""add search history table

Revision ID: 65f9c505e218
Revises: 08aaff3cbdeb
Create Date: 2018-03-04 14:35:26.408044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f9c505e218'
down_revision = '08aaff3cbdeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('query_word', sa.String(length=50), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('search_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_master_uid'), 'search_history', ['master_uid'], unique=False)
    op.create_index(op.f('ix_search_history_query_word'), 'search_history', ['query_word'], unique=False)
    op.drop_index('ix_product_statistics_master_uid', table_name='product_statistics')
    op.create_index(op.f('ix_product_statistics_master_uid'), 'product_statistics', ['master_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_statistics_master_uid'), table_name='product_statistics')
    op.create_index('ix_product_statistics_master_uid', 'product_statistics', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    op.drop_index(op.f('ix_search_history_query_word'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_master_uid'), table_name='search_history')
    op.drop_table('search_history')
    # ### end Alembic commands ###
