"""update stats table

Revision ID: 68bef3f3ac7c
Revises: a38864288c07
Create Date: 2018-05-12 10:31:01.375599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68bef3f3ac7c'
down_revision = 'a38864288c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('time', sa.String(length=8), nullable=False),
    sa.Column('income_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('income_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_uid', 'type', 'time')
    )
    op.create_index(op.f('ix_stats_master_master_uid'), 'stats_master', ['master_uid'], unique=False)
    op.create_table('stats_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('time', sa.String(length=8), nullable=False),
    sa.Column('income_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('income_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'type', 'time')
    )
    op.create_index(op.f('ix_stats_stores_master_uid'), 'stats_stores', ['master_uid'], unique=False)
    op.create_index(op.f('ix_stats_stores_store_id'), 'stats_stores', ['store_id'], unique=False)
    op.create_index('master_uid', 'stats_stores', ['time', 'store_id'], unique=False)
    op.create_table('stats_day_sku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku_id', 'time')
    )
    op.create_index(op.f('ix_stats_day_sku_category_id'), 'stats_day_sku', ['category_id'], unique=False)
    op.create_index(op.f('ix_stats_day_sku_master_uid'), 'stats_day_sku', ['master_uid'], unique=False)
    op.create_index(op.f('ix_stats_day_sku_product_id'), 'stats_day_sku', ['product_id'], unique=False)
    op.create_index(op.f('ix_stats_day_sku_sku_id'), 'stats_day_sku', ['sku_id'], unique=False)
    op.create_index(op.f('ix_stats_day_sku_sku_serial_no'), 'stats_day_sku', ['sku_serial_no'], unique=False)
    op.create_index(op.f('ix_stats_day_sku_store_id'), 'stats_day_sku', ['store_id'], unique=False)
    op.create_index(op.f('ix_stats_day_sku_supplier_id'), 'stats_day_sku', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_stats_day_sku_time'), 'stats_day_sku', ['time'], unique=False)
    op.create_table('stats_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('time', sa.String(length=8), nullable=False),
    sa.Column('time_type', sa.SmallInteger(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('income_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('income_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku_id', 'time', 'time_type')
    )
    op.create_index(op.f('ix_stats_products_master_uid'), 'stats_products', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    op.create_index(op.f('ix_stats_products_sku_serial_no'), 'stats_products', ['sku_serial_no'], unique=False)
    op.create_index(op.f('ix_stats_products_store_id'), 'stats_products', ['store_id'], unique=False)
    op.create_table('stats_sales_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('deal_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('create_at', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_sales_log_create_at'), 'stats_sales_log', ['create_at'], unique=False)
    op.create_index(op.f('ix_stats_sales_log_master_uid'), 'stats_sales_log', ['master_uid'], unique=False)
    op.create_index(op.f('ix_stats_sales_log_order_id'), 'stats_sales_log', ['order_id'], unique=False)
    op.create_index(op.f('ix_stats_sales_log_product_id'), 'stats_sales_log', ['product_id'], unique=False)
    op.create_index(op.f('ix_stats_sales_log_sku_serial_no'), 'stats_sales_log', ['sku_serial_no'], unique=False)
    op.create_index(op.f('ix_stats_sales_log_store_id'), 'stats_sales_log', ['store_id'], unique=False)
    op.drop_table('master_statistics')
    op.drop_table('store_statistics')
    op.drop_table('sales_log_statistics')
    op.drop_table('product_statistics')
    op.drop_table('day_sku_statistics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_sku_statistics',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('master_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sku_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sku_serial_no', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('supplier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('income', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('profit', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='day_sku_statistics_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='day_sku_statistics_ibfk_2'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], name='day_sku_statistics_ibfk_3'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='day_sku_statistics_ibfk_4'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='day_sku_statistics_ibfk_5'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('product_statistics',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('master_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sku_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('income', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('profit', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('time_type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('income_yoy', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('income_mom', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('profit_yoy', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('profit_mom', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sku_serial_no', mysql.VARCHAR(length=12), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], name='product_statistics_ibfk_1'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='product_statistics_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sales_log_statistics',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('master_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sku_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sku_serial_no', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('supplier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cost_price', mysql.FLOAT(), nullable=True),
    sa.Column('deal_price', mysql.FLOAT(), nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('discount_amount', mysql.FLOAT(), nullable=True),
    sa.Column('create_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='sales_log_statistics_ibfk_1'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='sales_log_statistics_ibfk_2'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='sales_log_statistics_ibfk_3'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], name='sales_log_statistics_ibfk_4'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='sales_log_statistics_ibfk_5'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='sales_log_statistics_ibfk_6'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('store_statistics',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('master_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('income', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('profit', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('time', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('income_yoy', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('income_mom', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('profit_yoy', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('profit_mom', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='store_statistics_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('master_statistics',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('master_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('income', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('profit', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('time', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('income_yoy', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('income_mom', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('profit_yoy', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('profit_mom', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_stats_sales_log_store_id'), table_name='stats_sales_log')
    op.drop_index(op.f('ix_stats_sales_log_sku_serial_no'), table_name='stats_sales_log')
    op.drop_index(op.f('ix_stats_sales_log_product_id'), table_name='stats_sales_log')
    op.drop_index(op.f('ix_stats_sales_log_order_id'), table_name='stats_sales_log')
    op.drop_index(op.f('ix_stats_sales_log_master_uid'), table_name='stats_sales_log')
    op.drop_index(op.f('ix_stats_sales_log_create_at'), table_name='stats_sales_log')
    op.drop_table('stats_sales_log')
    op.drop_index(op.f('ix_stats_products_store_id'), table_name='stats_products')
    op.drop_index(op.f('ix_stats_products_sku_serial_no'), table_name='stats_products')
    op.drop_index(op.f('ix_stats_products_master_uid'), table_name='stats_products')
    op.drop_table('stats_products')
    op.drop_index(op.f('ix_stats_day_sku_time'), table_name='stats_day_sku')
    op.drop_index(op.f('ix_stats_day_sku_supplier_id'), table_name='stats_day_sku')
    op.drop_index(op.f('ix_stats_day_sku_store_id'), table_name='stats_day_sku')
    op.drop_index(op.f('ix_stats_day_sku_sku_serial_no'), table_name='stats_day_sku')
    op.drop_index(op.f('ix_stats_day_sku_sku_id'), table_name='stats_day_sku')
    op.drop_index(op.f('ix_stats_day_sku_product_id'), table_name='stats_day_sku')
    op.drop_index(op.f('ix_stats_day_sku_master_uid'), table_name='stats_day_sku')
    op.drop_index(op.f('ix_stats_day_sku_category_id'), table_name='stats_day_sku')
    op.drop_table('stats_day_sku')
    op.drop_index('master_uid', table_name='stats_stores')
    op.drop_index(op.f('ix_stats_stores_store_id'), table_name='stats_stores')
    op.drop_index(op.f('ix_stats_stores_master_uid'), table_name='stats_stores')
    op.drop_table('stats_stores')
    op.drop_index(op.f('ix_stats_master_master_uid'), table_name='stats_master')
    op.drop_table('stats_master')
    # ### end Alembic commands ###
