"""remove store_id wx_mini_apps table

Revision ID: 69bd9e8a83f1
Revises: 47f6774e905c
Create Date: 2018-02-23 16:18:57.741262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69bd9e8a83f1'
down_revision = '47f6774e905c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wx_mini_apps_ibfk_1', 'wx_mini_apps', type_='foreignkey')
    op.drop_column('wx_mini_apps', 'store_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_mini_apps', sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('wx_mini_apps_ibfk_1', 'wx_mini_apps', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###
