"""add role title/decripton table

Revision ID: 6a6dc8a40f37
Revises: 61300564a73f
Create Date: 2017-06-10 23:32:23.581016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6dc8a40f37'
down_revision = '61300564a73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('roles', sa.Column('title', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'title')
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###
