"""add edition service table

Revision ID: 6aa621543cb2
Revises: f841bef95cd9
Create Date: 2018-04-18 14:51:47.565030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6aa621543cb2'
down_revision = 'f841bef95cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edition_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.SmallInteger(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['app_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('service_transactions')
    op.add_column('app_services', sa.Column('title', sa.String(length=50), nullable=False))
    op.drop_index('ix_app_services_name', table_name='app_services')
    op.create_index(op.f('ix_app_services_name'), 'app_services', ['name'], unique=True)
    op.add_column('subscribe_services', sa.Column('coupon_code', sa.String(length=16), nullable=True))
    op.add_column('subscribe_services', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('subscribe_services', sa.Column('ordered_days', sa.Integer(), nullable=True))
    op.add_column('subscribe_services', sa.Column('pay_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('subscribe_services', sa.Column('pay_mode', sa.SmallInteger(), nullable=True))
    op.add_column('subscribe_services', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('subscribe_services', sa.Column('trade_no', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_subscribe_services_trade_no'), 'subscribe_services', ['trade_no'], unique=True)
    op.drop_column('subscribe_services', 'expired_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe_services', sa.Column('expired_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_subscribe_services_trade_no'), table_name='subscribe_services')
    op.drop_column('subscribe_services', 'trade_no')
    op.drop_column('subscribe_services', 'total_amount')
    op.drop_column('subscribe_services', 'pay_mode')
    op.drop_column('subscribe_services', 'pay_amount')
    op.drop_column('subscribe_services', 'ordered_days')
    op.drop_column('subscribe_services', 'discount_amount')
    op.drop_column('subscribe_services', 'coupon_code')
    op.drop_index(op.f('ix_app_services_name'), table_name='app_services')
    op.create_index('ix_app_services_name', 'app_services', ['name'], unique=False)
    op.drop_column('app_services', 'title')
    op.create_table('service_transactions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('master_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sale_price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('pay_mode', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('discount_money', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ordered_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ordered_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['app_services.id'], name='service_transactions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('edition_services')
    # ### end Alembic commands ###
