"""update product statistics table

Revision ID: 6bcab6829582
Revises: 7d0c4ce7183d
Create Date: 2017-12-13 15:19:46.810918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcab6829582'
down_revision = '7d0c4ce7183d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_statistics', sa.Column('sku_serial_no', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_product_statistics_sku_serial_no'), 'product_statistics', ['sku_serial_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_statistics_sku_serial_no'), table_name='product_statistics')
    op.drop_column('product_statistics', 'sku_serial_no')
    # ### end Alembic commands ###
