"""add sku serial_no product_stock table

Revision ID: 6f96381020f3
Revises: 107dbbb75873
Create Date: 2017-06-29 12:48:19.583625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f96381020f3'
down_revision = '107dbbb75873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_stocks', sa.Column('sku_serial_no', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_product_stocks_sku_serial_no'), 'product_stocks', ['sku_serial_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_stocks_sku_serial_no'), table_name='product_stocks')
    op.drop_column('product_stocks', 'sku_serial_no')
    # ### end Alembic commands ###
