"""add time bonus table

Revision ID: 7217df118540
Revises: 81f210519ddf
Create Date: 2018-03-04 23:35:44.929051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7217df118540'
down_revision = '81f210519ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('bonus', sa.Column('updated_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bonus', 'updated_at')
    op.drop_column('bonus', 'created_at')
    # ### end Alembic commands ###
