"""add wx_pre_auth_codes table

Revision ID: 72264e9c53d1
Revises: d73e7320234a
Create Date: 2018-02-22 16:48:53.169893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72264e9c53d1'
down_revision = 'd73e7320234a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_pre_auth_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pre_auth_code', sa.String(length=100), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pre_auth_code')
    )
    op.add_column('wx_auth_codes', sa.Column('auth_code', sa.String(length=200), nullable=False))
    op.add_column('wx_auth_codes', sa.Column('master_uid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_wx_auth_codes_master_uid'), 'wx_auth_codes', ['master_uid'], unique=False)
    op.drop_index('ix_wx_auth_codes_app_id', table_name='wx_auth_codes')
    op.drop_index('pre_auth_code', table_name='wx_auth_codes')
    op.create_unique_constraint(None, 'wx_auth_codes', ['auth_code'])
    op.drop_column('wx_auth_codes', 'pre_auth_code')
    op.drop_column('wx_auth_codes', 'app_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_auth_codes', sa.Column('app_id', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('wx_auth_codes', sa.Column('pre_auth_code', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'wx_auth_codes', type_='unique')
    op.create_index('pre_auth_code', 'wx_auth_codes', ['pre_auth_code'], unique=True)
    op.create_index('ix_wx_auth_codes_app_id', 'wx_auth_codes', ['app_id'], unique=False)
    op.drop_index(op.f('ix_wx_auth_codes_master_uid'), table_name='wx_auth_codes')
    op.drop_column('wx_auth_codes', 'master_uid')
    op.drop_column('wx_auth_codes', 'auth_code')
    op.drop_table('wx_pre_auth_codes')
    # ### end Alembic commands ###
