"""modify supply_stats table

Revision ID: 739f39fa118c
Revises: 06181d27030b
Create Date: 2017-07-22 23:33:00.096450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '739f39fa118c'
down_revision = '06181d27030b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply_relevance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('sku_count', sa.Integer(), nullable=True),
    sa.Column('purchase_times', sa.Integer(), nullable=True),
    sa.Column('purchase_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('latest_trade_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_uid', 'supplier_id', name='uix_supply_master_uid_supplier_id')
    )
    op.create_index(op.f('ix_supply_relevance_created_at'), 'supply_relevance', ['created_at'], unique=False)
    op.create_index(op.f('ix_supply_relevance_master_uid'), 'supply_relevance', ['master_uid'], unique=False)
    op.drop_table('supply_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply_stats',
    sa.Column('master_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('supplier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sku_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('purchase_times', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('purchase_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('latest_trade_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='supply_stats_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_supply_relevance_master_uid'), table_name='supply_relevance')
    op.drop_index(op.f('ix_supply_relevance_created_at'), table_name='supply_relevance')
    op.drop_table('supply_relevance')
    # ### end Alembic commands ###
