"""add brand_rid product

Revision ID: 745f70ed6f65
Revises: dd53dbf97519
Create Date: 2017-11-30 15:06:39.269223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '745f70ed6f65'
down_revision = 'dd53dbf97519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_rid', sa.String(length=9), nullable=True))
    op.drop_constraint('products_ibfk_4', 'products', type_='foreignkey')
    op.drop_column('products', 'brand_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('products_ibfk_4', 'products', 'brands', ['brand_id'], ['id'])
    op.drop_column('products', 'brand_rid')
    # ### end Alembic commands ###
