"""remove supplier unique index

Revision ID: 74da0d6e3052
Revises: bd01abaec2ed
Create Date: 2017-07-21 15:28:31.240491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74da0d6e3052'
down_revision = 'bd01abaec2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_suppliers_full_name'), 'suppliers', ['full_name'], unique=False)
    op.create_index(op.f('ix_suppliers_short_name'), 'suppliers', ['short_name'], unique=False)
    op.drop_index('full_name', table_name='suppliers')
    op.drop_index('short_name', table_name='suppliers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('short_name', 'suppliers', ['short_name'], unique=True)
    op.create_index('full_name', 'suppliers', ['full_name'], unique=True)
    op.drop_index(op.f('ix_suppliers_short_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_full_name'), table_name='suppliers')
    # ### end Alembic commands ###
