"""remove unique table

Revision ID: 7974432d43a8
Revises: b458d8208954
Create Date: 2018-03-13 21:34:55.151543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7974432d43a8'
down_revision = 'b458d8208954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_brands_name', table_name='brands')
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.create_index('ix_brands_name', 'brands', ['name'], unique=True)
    # ### end Alembic commands ###
