"""add sn for user

Revision ID: 7bb2a8707fb6
Revises: 2b5075cda424
Create Date: 2017-11-22 21:48:10.323545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb2a8707fb6'
down_revision = '2b5075cda424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sn', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_users_sn'), 'users', ['sn'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sn'), table_name='users')
    op.drop_column('users', 'sn')
    # ### end Alembic commands ###
