"""add store platform table

Revision ID: 7c019aa44f06
Revises: 970e34270880
Create Date: 2017-06-13 00:17:43.717987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c019aa44f06'
down_revision = '970e34270880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('platform', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'platform')
    # ### end Alembic commands ###
