"""add type bonus table

Revision ID: 7e24e4145bea
Revises: 7217df118540
Create Date: 2018-03-05 11:58:20.151565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e24e4145bea'
down_revision = '7217df118540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus', sa.Column('reach_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bonus', sa.Column('type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bonus', 'type')
    op.drop_column('bonus', 'reach_amount')
    # ### end Alembic commands ###
