"""empty message

Revision ID: 7e82094aa100
Revises: d9deb8d9e47b
Create Date: 2018-05-09 13:56:45.714500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e82094aa100'
down_revision = 'd9deb8d9e47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('areacode', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'areacode')
    # ### end Alembic commands ###
