"""add name varchar 100 for suppliers table

Revision ID: 7f3048b98a93
Revises: ad688bfb2cab
Create Date: 2017-07-16 18:44:28.218184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3048b98a93'
down_revision = 'ad688bfb2cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('short_name', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'suppliers', ['short_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_column('suppliers', 'short_name')
    # ### end Alembic commands ###
