"""add product statistics table

Revision ID: 7fde97d87395
Revises: a279da9db3c3
Create Date: 2017-12-11 16:33:44.559430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fde97d87395'
down_revision = 'a279da9db3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('time', sa.String(length=8), nullable=False),
    sa.Column('time_type', sa.SmallInteger(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('income_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('income_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_statistics_master_uid'), 'product_statistics', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    op.create_index(op.f('ix_product_statistics_store_id'), 'product_statistics', ['store_id'], unique=False)
    op.create_foreign_key(None, 'store_statistics', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_statistics', type_='foreignkey')
    op.drop_index(op.f('ix_product_statistics_store_id'), table_name='product_statistics')
    op.drop_index(op.f('ix_product_statistics_master_uid'), table_name='product_statistics')
    op.drop_table('product_statistics')
    # ### end Alembic commands ###
