"""add serial_no product table

Revision ID: 80c78fffa8ec
Revises: 17677fb0670f
Create Date: 2017-08-09 01:16:55.825585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c78fffa8ec'
down_revision = '17677fb0670f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('serial_no', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_product_skus_serial_no'), 'product_skus', ['serial_no'], unique=True)
    op.add_column('products', sa.Column('serial_no', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_products_serial_no'), 'products', ['serial_no'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_serial_no'), table_name='products')
    op.drop_column('products', 'serial_no')
    op.drop_index(op.f('ix_product_skus_serial_no'), table_name='product_skus')
    op.drop_column('product_skus', 'serial_no')
    # ### end Alembic commands ###
