"""add search_times search_history table

Revision ID: 81f210519ddf
Revises: 65f9c505e218
Create Date: 2018-03-04 15:36:31.473105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f210519ddf'
down_revision = '65f9c505e218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('search_times', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'search_times')
    # ### end Alembic commands ###
