"""add total_count for product_packet

Revision ID: 8378e31b4908
Revises: 9cfc47fa1fd2
Create Date: 2017-12-08 14:21:34.579634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8378e31b4908'
down_revision = '9cfc47fa1fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_packets', 'total_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_packets', sa.Column('total_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
