"""add oid places table

Revision ID: 846ef592ebdd
Revises: aa6c6bcc733a
Create Date: 2018-02-26 15:09:49.975616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '846ef592ebdd'
down_revision = 'aa6c6bcc733a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('oid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'oid')
    # ### end Alembic commands ###
