"""add returned_count,manual_count product_stock table

Revision ID: 877147b8e706
Revises: 6f96381020f3
Create Date: 2017-06-29 22:09:47.395377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877147b8e706'
down_revision = '6f96381020f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_stocks', sa.Column('manual_count', sa.Integer(), nullable=True))
    op.add_column('product_stocks', sa.Column('returned_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_stocks', 'returned_count')
    op.drop_column('product_stocks', 'manual_count')
    # ### end Alembic commands ###
