"""add id supply_stats table

Revision ID: 87dfcbe418be
Revises: 74da0d6e3052
Create Date: 2017-07-22 23:21:13.563677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87dfcbe418be'
down_revision = '74da0d6e3052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supply_stats', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('supply_stats', 'master_uid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('supply_stats', 'supplier_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_unique_constraint('uix_supply_master_uid_supplier_id', 'supply_stats', ['master_uid', 'supplier_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_supply_master_uid_supplier_id', 'supply_stats', type_='unique')
    op.alter_column('supply_stats', 'supplier_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('supply_stats', 'master_uid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('supply_stats', 'id')
    # ### end Alembic commands ###
