"""remove unique_index directory table

Revision ID: 886f408d8ffd
Revises: 739f39fa118c
Create Date: 2017-07-24 00:26:09.375041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886f408d8ffd'
down_revision = '739f39fa118c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_directories_name', table_name='directories')
    op.create_index(op.f('ix_directories_name'), 'directories', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directories_name'), table_name='directories')
    op.create_index('ix_directories_name', 'directories', ['name'], unique=True)
    # ### end Alembic commands ###
