"""add receive_ur for client

Revision ID: 8b697e0ddf39
Revises: 2a5c0b59f0f9
Create Date: 2017-11-21 11:51:14.550000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b697e0ddf39'
down_revision = '2a5c0b59f0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('receive_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'receive_url')
    # ### end Alembic commands ###
