"""add fail_reason wx_version table

Revision ID: 8e38c081ef15
Revises: 7974432d43a8
Create Date: 2018-03-14 17:36:45.305711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e38c081ef15'
down_revision = '7974432d43a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_versions', sa.Column('fail_at', sa.Integer(), nullable=True))
    op.add_column('wx_versions', sa.Column('fail_reason', sa.Text(), nullable=True))
    op.add_column('wx_versions', sa.Column('success_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wx_versions', 'success_at')
    op.drop_column('wx_versions', 'fail_reason')
    op.drop_column('wx_versions', 'fail_at')
    # ### end Alembic commands ###
