"""remove foreighkey order_items

Revision ID: 8e3808edf29e
Revises: 948bae925e0a
Create Date: 2018-03-15 01:15:31.361216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3808edf29e'
down_revision = '948bae925e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_ibfk_3', 'order_items', type_='foreignkey')
    op.drop_index('ix_product_statistics_master_uid', table_name='product_statistics')
    op.create_index(op.f('ix_product_statistics_master_uid'), 'product_statistics', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_statistics_master_uid'), table_name='product_statistics')
    op.create_index('ix_product_statistics_master_uid', 'product_statistics', ['master_uid'], unique=False)
    op.create_foreign_key('order_items_ibfk_3', 'order_items', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###
