"""add arrival_at for purchase table

Revision ID: 943e0f546aeb
Revises: 338dc5c498b1
Create Date: 2017-07-15 17:03:07.942071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943e0f546aeb'
down_revision = '338dc5c498b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('arrival_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'arrival_at')
    # ### end Alembic commands ###
