"""add belong store user

Revision ID: 9467c9625bfe
Revises: 056450af10ba
Create Date: 2018-04-11 13:55:10.644191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9467c9625bfe'
down_revision = '056450af10ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('store_id', sa.Integer(), nullable=True))
    op.drop_column('users', 'belong_store')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('belong_store', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('users', 'store_id')
    # ### end Alembic commands ###
