"""add features for product

Revision ID: 948bae925e0a
Revises: 8e38c081ef15
Create Date: 2018-03-14 23:29:15.171819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948bae925e0a'
down_revision = '8e38c081ef15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('features', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'features')
    # ### end Alembic commands ###
