"""add sku_serial_no for purchase_product table

Revision ID: 97aeb14dfa8f
Revises: 3e4fe2d9a72b
Create Date: 2017-07-09 22:48:11.233992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97aeb14dfa8f'
down_revision = '3e4fe2d9a72b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_product', sa.Column('sku_serial_no', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_purchase_product_sku_serial_no'), 'purchase_product', ['sku_serial_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_product_sku_serial_no'), table_name='purchase_product')
    op.drop_column('purchase_product', 'sku_serial_no')
    # ### end Alembic commands ###
