"""add buyer_town order

Revision ID: 9969f9be43cb
Revises: bb1f5bdfe9cc
Create Date: 2017-12-30 23:42:51.084734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9969f9be43cb'
down_revision = 'bb1f5bdfe9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('buyer_town', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'buyer_town')
    # ### end Alembic commands ###
