"""remove warehouse_shelve for inwarehouse table

Revision ID: 99f39e0e6de0
Revises: a6dcf5b20e5c
Create Date: 2017-07-11 00:48:38.502932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99f39e0e6de0'
down_revision = 'a6dcf5b20e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('warehouse_in_list_ibfk_2', 'warehouse_in_list', type_='foreignkey')
    op.drop_column('warehouse_in_list', 'warehouse_shelve_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_in_list', sa.Column('warehouse_shelve_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('warehouse_in_list_ibfk_2', 'warehouse_in_list', 'warehouse_shelves', ['warehouse_shelve_id'], ['id'])
    # ### end Alembic commands ###
