"""update master statistics

Revision ID: 9b7c8e60febc
Revises: 3dcd010f1d46
Create Date: 2017-12-22 15:29:29.940958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7c8e60febc'
down_revision = '3dcd010f1d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'master_statistics', ['master_uid', 'type', 'time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'master_statistics', type_='unique')
    # ### end Alembic commands ###
