"""update product statistics table

Revision ID: 9ba3a952d2db
Revises: 7fde97d87395
Create Date: 2017-12-11 17:17:39.951138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba3a952d2db'
down_revision = '7fde97d87395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_statistics', sa.Column('count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_statistics', 'count')
    # ### end Alembic commands ###
