"""add brand_id for product

Revision ID: 9cfc47fa1fd2
Revises: c246d4c91747
Create Date: 2017-12-08 10:17:00.967968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cfc47fa1fd2'
down_revision = 'c246d4c91747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.drop_column('products', 'brand_rid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_rid', mysql.VARCHAR(length=9), nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'brand_id')
    # ### end Alembic commands ###
