"""add master_uid for stock_history table

Revision ID: 9e6c6903ddad
Revises: deb2e8aab4fc
Create Date: 2017-07-09 23:31:51.149283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6c6903ddad'
down_revision = 'deb2e8aab4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_stocks', sa.Column('master_uid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_stocks_master_uid'), 'product_stocks', ['master_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_stocks_master_uid'), table_name='product_stocks')
    op.drop_column('product_stocks', 'master_uid')
    # ### end Alembic commands ###
