"""update warehouse stock history table

Revision ID: a0f55b5a8ee5
Revises: f6f76963b293
Create Date: 2017-06-28 11:03:37.619322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0f55b5a8ee5'
down_revision = 'f6f76963b293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_stock_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('product_sku_id', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=True),
    sa.Column('original_quantity', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('current_quantity', sa.Integer(), nullable=True),
    sa.Column('ori_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_stock_history_master_uid'), 'warehouse_stock_history', ['master_uid'], unique=False)
    op.create_index(op.f('ix_warehouse_stock_history_serial_no'), 'warehouse_stock_history', ['serial_no'], unique=False)
    op.drop_table('warehouse_out_products')
    op.drop_table('warehouse_in_products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_in_products',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('in_warehouse_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('product_sku_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('in_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('new_price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('new_stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ori_price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ori_stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['in_warehouse_id'], ['warehouse_in_list.id'], name='warehouse_in_products_ibfk_1'),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], name='warehouse_in_products_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('warehouse_out_products',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('out_warehouse_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('product_sku_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('out_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['out_warehouse_id'], ['warehouse_out_list.id'], name='warehouse_out_products_ibfk_1'),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], name='warehouse_out_products_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_warehouse_stock_history_serial_no'), table_name='warehouse_stock_history')
    op.drop_index(op.f('ix_warehouse_stock_history_master_uid'), table_name='warehouse_stock_history')
    op.drop_table('warehouse_stock_history')
    # ### end Alembic commands ###
