"""add is_default for asset/directory table

Revision ID: a17c28a49748
Revises: 943e0f546aeb
Create Date: 2017-07-16 13:58:52.495404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17c28a49748'
down_revision = '943e0f546aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('directories', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('finished_at', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('received_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'received_at')
    op.drop_column('orders', 'finished_at')
    op.drop_column('directories', 'is_default')
    op.drop_column('assets', 'is_default')
    # ### end Alembic commands ###
