"""update statistics table

Revision ID: a279da9db3c3
Revises: ceb078081704
Create Date: 2017-12-05 17:13:44.967195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a279da9db3c3'
down_revision = 'ceb078081704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_statistics', sa.Column('income_mom', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('master_statistics', sa.Column('income_yoy', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('master_statistics', sa.Column('profit_mom', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('master_statistics', sa.Column('profit_yoy', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_index('master_uid', 'master_statistics', ['time'], unique=False)
    op.add_column('store_statistics', sa.Column('income_mom', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('store_statistics', sa.Column('income_yoy', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('store_statistics', sa.Column('profit_mom', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('store_statistics', sa.Column('profit_yoy', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_index('master_uid', 'store_statistics', ['time', 'store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('master_uid', table_name='store_statistics')
    op.drop_column('store_statistics', 'profit_yoy')
    op.drop_column('store_statistics', 'profit_mom')
    op.drop_column('store_statistics', 'income_yoy')
    op.drop_column('store_statistics', 'income_mom')
    op.drop_index('master_uid', table_name='master_statistics')
    op.drop_column('master_statistics', 'profit_yoy')
    op.drop_column('master_statistics', 'profit_mom')
    op.drop_column('master_statistics', 'income_yoy')
    op.drop_column('master_statistics', 'income_mom')
    # ### end Alembic commands ###
