"""add user_id for customer

Revision ID: a48df7bf58fe
Revises: 555fd0d48e73
Create Date: 2017-12-06 23:13:00.137206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48df7bf58fe'
down_revision = '555fd0d48e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'user_id')
    # ### end Alembic commands ###
