"""update supplier table

Revision ID: a5ea32ec0125
Revises: 9c06ef731b9c
Create Date: 2017-06-14 17:05:05.120763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ea32ec0125'
down_revision = '9c06ef731b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('updated_at', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_suppliers_created_at'), 'suppliers', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_created_at'), table_name='suppliers')
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'created_at')
    # ### end Alembic commands ###
