"""add is_default for warehouse_shelves table

Revision ID: a6dcf5b20e5c
Revises: e18459cd039b
Create Date: 2017-07-10 21:21:50.135504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6dcf5b20e5c'
down_revision = 'e18459cd039b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_shelves', sa.Column('is_default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse_shelves', 'is_default')
    # ### end Alembic commands ###
