"""add master_uid into tables

Revision ID: a98dae0a5b4a
Revises: d17a54320a15
Create Date: 2017-06-22 19:09:40.456385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a98dae0a5b4a'
down_revision = 'd17a54320a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('master_uid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assets_master_uid'), 'assets', ['master_uid'], unique=False)
    op.drop_column('assets', 'user_id')
    op.add_column('directories', sa.Column('master_uid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_directories_master_uid'), 'directories', ['master_uid'], unique=False)
    op.drop_column('directories', 'user_id')
    op.add_column('purchases', sa.Column('master_uid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchases_master_uid'), 'purchases', ['master_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_master_uid'), table_name='purchases')
    op.drop_column('purchases', 'master_uid')
    op.add_column('directories', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_directories_master_uid'), table_name='directories')
    op.drop_column('directories', 'master_uid')
    op.add_column('assets', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_assets_master_uid'), table_name='assets')
    op.drop_column('assets', 'master_uid')
    # ### end Alembic commands ###
