"""add 3rd field user table

Revision ID: aa6c6bcc733a
Revises: 69bd9e8a83f1
Create Date: 2018-02-24 13:33:36.394748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6c6bcc733a'
down_revision = '69bd9e8a83f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_statistics_master_uid', table_name='product_statistics')
    op.create_index(op.f('ix_product_statistics_master_uid'), 'product_statistics', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('gender', sa.SmallInteger(), nullable=True))
    op.add_column('users', sa.Column('openid', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('province', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('referer', sa.SmallInteger(), nullable=True))
    op.add_column('users', sa.Column('unionid', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=False)
    op.create_index(op.f('ix_users_unionid'), 'users', ['unionid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_unionid'), table_name='users')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_column('users', 'unionid')
    op.drop_column('users', 'referer')
    op.drop_column('users', 'province')
    op.drop_column('users', 'openid')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_index(op.f('ix_product_statistics_master_uid'), table_name='product_statistics')
    op.create_index('ix_product_statistics_master_uid', 'product_statistics', ['master_uid'], unique=False)
    # ### end Alembic commands ###
