"""add name varchar 100 for suppliers table

Revision ID: ad688bfb2cab
Revises: 39bf392ad9c0
Create Date: 2017-07-16 18:43:50.418311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad688bfb2cab'
down_revision = '39bf392ad9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='suppliers')
    op.drop_column('suppliers', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('name', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False))
    op.create_index('name', 'suppliers', ['name'], unique=True)
    # ### end Alembic commands ###
