"""add wx_mini_apps table

Revision ID: af2cb945b548
Revises: cd809416a850
Create Date: 2018-02-23 15:15:08.229408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af2cb945b548'
down_revision = 'cd809416a850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_mini_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=32), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.String(length=20), nullable=False),
    sa.Column('nick_name', sa.String(length=100), nullable=False),
    sa.Column('head_img', sa.String(length=200), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('principal_name', sa.String(length=64), nullable=True),
    sa.Column('service_type_info', sa.String(length=100), nullable=True),
    sa.Column('verify_type_info', sa.String(length=100), nullable=True),
    sa.Column('business_info', sa.String(length=100), nullable=True),
    sa.Column('qrcode_url', sa.String(length=200), nullable=True),
    sa.Column('mini_program_info', sa.Text(), nullable=True),
    sa.Column('func_info', sa.Text(), nullable=False),
    sa.Column('location_report', sa.SmallInteger(), nullable=True),
    sa.Column('voice_recognize', sa.SmallInteger(), nullable=True),
    sa.Column('customer_service', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('default_country', sa.Integer(), nullable=True),
    sa.Column('default_language', sa.Integer(), nullable=True),
    sa.Column('default_currency', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wx_mini_apps_app_id'), 'wx_mini_apps', ['app_id'], unique=False)
    op.create_index(op.f('ix_wx_mini_apps_master_uid'), 'wx_mini_apps', ['master_uid'], unique=False)
    op.create_index(op.f('ix_wx_mini_apps_nick_name'), 'wx_mini_apps', ['nick_name'], unique=False)
    op.create_index(op.f('ix_wx_mini_apps_serial_no'), 'wx_mini_apps', ['serial_no'], unique=True)
    op.drop_table('wx_authorizer_info')
    op.drop_index('ix_product_statistics_master_uid', table_name='product_statistics')
    op.create_index(op.f('ix_product_statistics_master_uid'), 'product_statistics', ['master_uid'], unique=False)
    op.add_column('wx_auth_codes', sa.Column('auth_app_id', sa.String(length=32), nullable=True))
    op.drop_column('wx_auth_codes', 'app_id')
    op.add_column('wx_authorizer', sa.Column('auth_app_id', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_wx_authorizer_auth_app_id'), 'wx_authorizer', ['auth_app_id'], unique=False)
    op.drop_index('ix_wx_authorizer_app_id', table_name='wx_authorizer')
    op.drop_column('wx_authorizer', 'app_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_authorizer', sa.Column('app_id', mysql.VARCHAR(length=20), nullable=False))
    op.create_index('ix_wx_authorizer_app_id', 'wx_authorizer', ['app_id'], unique=False)
    op.drop_index(op.f('ix_wx_authorizer_auth_app_id'), table_name='wx_authorizer')
    op.drop_column('wx_authorizer', 'auth_app_id')
    op.add_column('wx_auth_codes', sa.Column('app_id', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('wx_auth_codes', 'auth_app_id')
    op.drop_index(op.f('ix_product_statistics_master_uid'), table_name='product_statistics')
    op.create_index('ix_product_statistics_master_uid', 'product_statistics', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    op.create_table('wx_authorizer_info',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('master_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('app_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nick_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('head_img', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('signature', mysql.TEXT(), nullable=True),
    sa.Column('principal_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('service_type_info', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('verify_type_info', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('business_info', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('qrcode_url', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('mini_program_info', mysql.TEXT(), nullable=True),
    sa.Column('func_info', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('update_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_wx_mini_apps_serial_no'), table_name='wx_mini_apps')
    op.drop_index(op.f('ix_wx_mini_apps_nick_name'), table_name='wx_mini_apps')
    op.drop_index(op.f('ix_wx_mini_apps_master_uid'), table_name='wx_mini_apps')
    op.drop_index(op.f('ix_wx_mini_apps_app_id'), table_name='wx_mini_apps')
    op.drop_table('wx_mini_apps')
    # ### end Alembic commands ###
