"""add address_id order

Revision ID: b17b891ad0bb
Revises: 6d9d4eedf456
Create Date: 2018-01-01 22:16:56.105545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17b891ad0bb'
down_revision = '6d9d4eedf456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'])
    op.drop_index('ix_product_statistics_master_uid', table_name='product_statistics')
    op.create_index(op.f('ix_product_statistics_master_uid'), 'product_statistics', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_statistics_master_uid'), table_name='product_statistics')
    op.create_index('ix_product_statistics_master_uid', 'product_statistics', ['master_uid'], unique=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'address_id')
    # ### end Alembic commands ###
