"""add store_id warehouse table

Revision ID: b42612d3bcdf
Revises: 28b6f51b3f61
Create Date: 2018-04-12 21:31:00.137453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42612d3bcdf'
down_revision = '28b6f51b3f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('store_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'store_id')
    # ### end Alembic commands ###
