"""remove foreignkey table

Revision ID: b458d8208954
Revises: 56ea592e0512
Create Date: 2018-03-13 11:49:44.424363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b458d8208954'
down_revision = '56ea592e0512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_skus_ibfk_3', 'product_skus', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('product_skus_ibfk_3', 'product_skus', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###
