"""add width height banner

Revision ID: b88684c40b90
Revises: 2bf47066ddd7
Create Date: 2018-01-02 19:26:12.428395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88684c40b90'
down_revision = '2bf47066ddd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('banners', sa.Column('width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banners', 'width')
    op.drop_column('banners', 'height')
    # ### end Alembic commands ###
