"""add created_at/updated_at for product table

Revision ID: b9effe1f5f87
Revises: e8a6ef39891c
Create Date: 2017-06-15 15:53:09.125123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9effe1f5f87'
down_revision = 'e8a6ef39891c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
