"""add serial_no address

Revision ID: bb1f5bdfe9cc
Revises: 5f53fd101465
Create Date: 2017-12-29 13:04:26.590612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1f5bdfe9cc'
down_revision = '5f53fd101465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('serial_no', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_addresses_serial_no'), 'addresses', ['serial_no'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_addresses_serial_no'), table_name='addresses')
    op.drop_column('addresses', 'serial_no')
    # ### end Alembic commands ###
