"""add prduct sku id into tables

Revision ID: bbf70cd44a63
Revises: a98dae0a5b4a
Create Date: 2017-06-22 19:33:24.929250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbf70cd44a63'
down_revision = 'a98dae0a5b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=2), nullable=False),
    sa.Column('contact_name', sa.String(length=16), nullable=False),
    sa.Column('contact_mobile', sa.String(length=11), nullable=True),
    sa.Column('contact_phone', sa.String(length=11), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expresses_company'), 'expresses', ['company'], unique=False)
    op.create_index(op.f('ix_expresses_master_uid'), 'expresses', ['master_uid'], unique=False)
    op.create_index(op.f('ix_expresses_name'), 'expresses', ['name'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('outside_target_id', sa.String(length=32), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('pay_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('freight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('express_id', sa.Integer(), nullable=True),
    sa.Column('express_no', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('invoice_type', sa.SmallInteger(), nullable=True),
    sa.Column('buyer_name', sa.String(length=50), nullable=False),
    sa.Column('buyer_tel', sa.String(length=20), nullable=True),
    sa.Column('buyer_phone', sa.String(length=20), nullable=True),
    sa.Column('buyer_zipcode', sa.String(length=16), nullable=True),
    sa.Column('buyer_address', sa.String(length=200), nullable=True),
    sa.Column('buyer_country', sa.String(length=50), nullable=True),
    sa.Column('buyer_province', sa.String(length=50), nullable=True),
    sa.Column('buyer_city', sa.String(length=50), nullable=True),
    sa.Column('buyer_remark', sa.String(length=250), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('suspend', sa.Boolean(), nullable=True),
    sa.Column('expired_time', sa.Integer(), nullable=True),
    sa.Column('from_client', sa.SmallInteger(), nullable=True),
    sa.Column('affiliate_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.Integer(), nullable=True),
    sa.Column('payed_at', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['express_id'], ['expresses.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_buyer_name'), 'order', ['buyer_name'], unique=False)
    op.create_index(op.f('ix_order_buyer_phone'), 'order', ['buyer_phone'], unique=False)
    op.create_index(op.f('ix_order_buyer_tel'), 'order', ['buyer_tel'], unique=False)
    op.create_index(op.f('ix_order_master_uid'), 'order', ['master_uid'], unique=False)
    op.create_index(op.f('ix_order_outside_target_id'), 'order', ['outside_target_id'], unique=False)
    op.create_index(op.f('ix_order_serial_no'), 'order', ['serial_no'], unique=True)
    op.create_table('shippers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('from_city', sa.String(length=32), nullable=False),
    sa.Column('province', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shippers_from_city'), 'shippers', ['from_city'], unique=False)
    op.create_index(op.f('ix_shippers_master_uid'), 'shippers', ['master_uid'], unique=False)
    op.add_column('purchase_product', sa.Column('product_sku_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_product', 'product_skus', ['product_sku_id'], ['id'])
    op.drop_column('purchase_product', 'sku_serial_no')
    op.add_column('purchase_returned_products', sa.Column('product_sku_id', sa.Integer(), nullable=True))
    op.drop_constraint('purchase_returned_products_ibfk_2', 'purchase_returned_products', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_returned_products', 'product_skus', ['product_sku_id'], ['id'])
    op.drop_column('purchase_returned_products', 'sku_id')
    op.add_column('users', sa.Column('master_uid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_master_uid'), 'users', ['master_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_master_uid'), table_name='users')
    op.drop_column('users', 'master_uid')
    op.add_column('purchase_returned_products', sa.Column('sku_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchase_returned_products', type_='foreignkey')
    op.create_foreign_key('purchase_returned_products_ibfk_2', 'purchase_returned_products', 'product_skus', ['sku_id'], ['id'])
    op.drop_column('purchase_returned_products', 'product_sku_id')
    op.add_column('purchase_product', sa.Column('sku_serial_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchase_product', type_='foreignkey')
    op.drop_column('purchase_product', 'product_sku_id')
    op.drop_index(op.f('ix_shippers_master_uid'), table_name='shippers')
    op.drop_index(op.f('ix_shippers_from_city'), table_name='shippers')
    op.drop_table('shippers')
    op.drop_index(op.f('ix_order_serial_no'), table_name='order')
    op.drop_index(op.f('ix_order_outside_target_id'), table_name='order')
    op.drop_index(op.f('ix_order_master_uid'), table_name='order')
    op.drop_index(op.f('ix_order_buyer_tel'), table_name='order')
    op.drop_index(op.f('ix_order_buyer_phone'), table_name='order')
    op.drop_index(op.f('ix_order_buyer_name'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_expresses_name'), table_name='expresses')
    op.drop_index(op.f('ix_expresses_master_uid'), table_name='expresses')
    op.drop_index(op.f('ix_expresses_company'), table_name='expresses')
    op.drop_table('expresses')
    # ### end Alembic commands ###
