"""add is_setting user table

Revision ID: bbfc02507791
Revises: 526f47c882c7
Create Date: 2017-07-02 21:35:11.135751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbfc02507791'
down_revision = '526f47c882c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('language', mysql.VARCHAR(length=4), nullable=True))
    # ### end Alembic commands ###
