"""add relation uid order

Revision ID: bc44ec94f137
Revises: b17b891ad0bb
Create Date: 2018-01-02 00:33:32.123350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc44ec94f137'
down_revision = 'b17b891ad0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('deliver_uid', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('saler_uid', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('service_uid', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('verified_uid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'verified_uid')
    op.drop_column('orders', 'service_uid')
    op.drop_column('orders', 'saler_uid')
    op.drop_column('orders', 'deliver_uid')
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###
