"""add supply_stats table

Revision ID: bd01abaec2ed
Revises: c4ccb56949c2
Create Date: 2017-07-21 14:17:16.571467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd01abaec2ed'
down_revision = 'c4ccb56949c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply_stats',
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('sku_count', sa.Integer(), nullable=True),
    sa.Column('purchase_times', sa.Integer(), nullable=True),
    sa.Column('purchase_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('latest_trade_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('master_uid', 'supplier_id')
    )
    op.create_index(op.f('ix_supply_stats_created_at'), 'supply_stats', ['created_at'], unique=False)
    op.create_index(op.f('ix_supply_stats_master_uid'), 'supply_stats', ['master_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supply_stats_master_uid'), table_name='supply_stats')
    op.drop_index(op.f('ix_supply_stats_created_at'), table_name='supply_stats')
    op.drop_table('supply_stats')
    # ### end Alembic commands ###
