"""add code for express

Revision ID: c08f55b4a662
Revises: 5ae6e612025a
Create Date: 2017-09-06 14:46:03.786324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08f55b4a662'
down_revision = '5ae6e612025a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expresses', sa.Column('code', sa.String(length=10), nullable=False))
    op.create_index(op.f('ix_expresses_code'), 'expresses', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expresses_code'), table_name='expresses')
    op.drop_column('expresses', 'code')
    # ### end Alembic commands ###
