"""add mode store table

Revision ID: c3e1e6fc15c8
Revises: b42612d3bcdf
Create Date: 2018-04-12 23:43:50.938942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e1e6fc15c8'
down_revision = 'b42612d3bcdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('distribute_mode', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'distribute_mode')
    # ### end Alembic commands ###
