"""update warehouse shelve unique index

Revision ID: c4ccb56949c2
Revises: 1b581e8043ab
Create Date: 2017-07-20 16:38:58.939894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ccb56949c2'
down_revision = '1b581e8043ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_warehouse_shelves_name'), 'warehouse_shelves', ['name'], unique=False)
    op.drop_index('name', table_name='warehouse_shelves')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'warehouse_shelves', ['name'], unique=True)
    op.drop_index(op.f('ix_warehouse_shelves_name'), table_name='warehouse_shelves')
    # ### end Alembic commands ###
