"""add status store_products table

Revision ID: c7e2972e4eea
Revises: 454c7f485814
Create Date: 2018-04-23 16:19:44.851375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e2972e4eea'
down_revision = '454c7f485814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_products', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_products', 'status')
    # ### end Alembic commands ###
