"""add related_rid to order

Revision ID: cba4bc28cc67
Revises: 3841d5a8e12c
Create Date: 2017-10-22 00:22:09.516111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba4bc28cc67'
down_revision = '3841d5a8e12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('related_rid', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'related_rid')
    # ### end Alembic commands ###
