"""modify field type for order/order_item table

Revision ID: cc1da38474ce
Revises: 4c39dbc3fe23
Create Date: 2017-07-01 15:34:26.320787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1da38474ce'
down_revision = '4c39dbc3fe23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('orders_ibfk_1', 'orders', 'expresses', ['express_id'], ['id'])
    # ### end Alembic commands ###
