"""add sales log statistics table

Revision ID: cd9ea43f9999
Revises: 6bcab6829582
Create Date: 2017-12-18 11:29:16.241684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9ea43f9999'
down_revision = '6bcab6829582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_log_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('deal_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('create_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_log_statistics_create_at'), 'sales_log_statistics', ['create_at'], unique=False)
    op.create_index(op.f('ix_sales_log_statistics_master_uid'), 'sales_log_statistics', ['master_uid'], unique=False)
    op.create_index(op.f('ix_sales_log_statistics_order_id'), 'sales_log_statistics', ['order_id'], unique=False)
    op.create_index(op.f('ix_sales_log_statistics_sku_serial_no'), 'sales_log_statistics', ['sku_serial_no'], unique=False)
    op.create_index(op.f('ix_sales_log_statistics_store_id'), 'sales_log_statistics', ['store_id'], unique=False)
    op.drop_index('ix_product_statistics_master_uid', table_name='product_statistics')
    op.create_index(op.f('ix_product_statistics_master_uid'), 'product_statistics', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_statistics_master_uid'), table_name='product_statistics')
    op.create_index('ix_product_statistics_master_uid', 'product_statistics', ['master_uid'], unique=False)
    op.drop_index(op.f('ix_sales_log_statistics_store_id'), table_name='sales_log_statistics')
    op.drop_index(op.f('ix_sales_log_statistics_sku_serial_no'), table_name='sales_log_statistics')
    op.drop_index(op.f('ix_sales_log_statistics_order_id'), table_name='sales_log_statistics')
    op.drop_index(op.f('ix_sales_log_statistics_master_uid'), table_name='sales_log_statistics')
    op.drop_index(op.f('ix_sales_log_statistics_create_at'), table_name='sales_log_statistics')
    op.drop_table('sales_log_statistics')
    # ### end Alembic commands ###
