"""add title for ability table

Revision ID: cdf7905cf080
Revises: f46c5669750f
Create Date: 2017-07-02 15:23:01.273975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf7905cf080'
down_revision = 'f46c5669750f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abilities', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abilities', 'title')
    # ### end Alembic commands ###
