"""add is_default for express/supplier table

Revision ID: ce2e7c691bd6
Revises: a17c28a49748
Create Date: 2017-07-16 17:13:03.140418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2e7c691bd6'
down_revision = 'a17c28a49748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expresses', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('suppliers', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('suppliers', 'is_default')
    op.drop_column('expresses', 'is_default')
    # ### end Alembic commands ###
