"""add statistics table

Revision ID: ceb078081704
Revises: 620c713140b6
Create Date: 2017-12-04 14:45:02.087203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb078081704'
down_revision = '620c713140b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('time', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_statistics_master_uid'), 'master_statistics', ['master_uid'], unique=False)
    op.create_table('store_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('time', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_statistics_master_uid'), 'store_statistics', ['master_uid'], unique=False)
    op.create_index(op.f('ix_store_statistics_store_id'), 'store_statistics', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_statistics_store_id'), table_name='store_statistics')
    op.drop_index(op.f('ix_store_statistics_master_uid'), table_name='store_statistics')
    op.drop_table('store_statistics')
    op.drop_index(op.f('ix_master_statistics_master_uid'), table_name='master_statistics')
    op.drop_table('master_statistics')
    # ### end Alembic commands ###
