"""modify product serial_no table

Revision ID: d17a54320a15
Revises: d439834ba5e3
Create Date: 2017-06-22 19:03:14.610225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd17a54320a15'
down_revision = 'd439834ba5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_exchange_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('out_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('in_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('out_in_status', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_user_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_exchange_list_master_uid'), 'warehouse_exchange_list', ['master_uid'], unique=False)
    op.create_index(op.f('ix_warehouse_exchange_list_serial_no'), 'warehouse_exchange_list', ['serial_no'], unique=True)
    op.create_table('warehouse_in_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.SmallInteger(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('in_quantity', sa.Integer(), nullable=True),
    sa.Column('in_status', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_in_list_master_uid'), 'warehouse_in_list', ['master_uid'], unique=False)
    op.create_index(op.f('ix_warehouse_in_list_serial_no'), 'warehouse_in_list', ['serial_no'], unique=True)
    op.create_table('warehouse_out_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.SmallInteger(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('out_quantity', sa.Integer(), nullable=True),
    sa.Column('out_status', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_out_list_master_uid'), 'warehouse_out_list', ['master_uid'], unique=False)
    op.create_index(op.f('ix_warehouse_out_list_serial_no'), 'warehouse_out_list', ['serial_no'], unique=True)
    op.create_table('purchase_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.Integer(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('in_quantity', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('freight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_returned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('outed_quantity', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_user_id', sa.Integer(), nullable=True),
    sa.Column('outed_status', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_returned_serial_no'), 'purchase_returned', ['serial_no'], unique=True)
    op.create_table('product_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_sku_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_shelve_id', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('saled_count', sa.Integer(), nullable=True),
    sa.Column('min_count', sa.Integer(), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['warehouse_shelve_id'], ['warehouse_shelves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_stocks_created_at'), 'product_stocks', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_stocks_product_sku_id'), 'product_stocks', ['product_sku_id'], unique=False)
    op.create_index(op.f('ix_product_stocks_warehouse_id'), 'product_stocks', ['warehouse_id'], unique=False)
    op.create_table('purchase_returned_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_returned_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('returned_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('returned_quantity', sa.Integer(), nullable=True),
    sa.Column('outed_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_returned_id'], ['purchase_returned.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_exchange_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('product_sku_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_warehouse_id'], ['warehouse_exchange_list.id'], ),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_in_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('in_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('product_sku_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('in_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['in_warehouse_id'], ['warehouse_in_list.id'], ),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_out_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('out_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('product_sku_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('out_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['out_warehouse_id'], ['warehouse_out_list.id'], ),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('purchase_products')
    op.add_column('stores', sa.Column('access_token', sa.String(length=100), nullable=True))
    op.add_column('stores', sa.Column('authorize_expired_at', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('master_uid', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('refresh_token', sa.String(length=100), nullable=True))
    op.drop_column('stores', 'user_id')
    op.add_column('warehouses', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('warehouses', sa.Column('master_uid', sa.Integer(), nullable=True))
    op.add_column('warehouses', sa.Column('updated_at', sa.Integer(), nullable=True))
    op.drop_column('warehouses', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('warehouses', 'updated_at')
    op.drop_column('warehouses', 'master_uid')
    op.drop_column('warehouses', 'created_at')
    op.add_column('stores', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('stores', 'refresh_token')
    op.drop_column('stores', 'master_uid')
    op.drop_column('stores', 'authorize_expired_at')
    op.drop_column('stores', 'access_token')
    op.create_table('purchase_products',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('purchase_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sku_serial_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cost_price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('in_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tax_rate', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('freight', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name='purchase_products_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('warehouse_out_products')
    op.drop_table('warehouse_in_products')
    op.drop_table('warehouse_exchange_products')
    op.drop_table('purchase_returned_products')
    op.drop_index(op.f('ix_product_stocks_warehouse_id'), table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_product_sku_id'), table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_created_at'), table_name='product_stocks')
    op.drop_table('product_stocks')
    op.drop_index(op.f('ix_purchase_returned_serial_no'), table_name='purchase_returned')
    op.drop_table('purchase_returned')
    op.drop_table('purchase_product')
    op.drop_index(op.f('ix_warehouse_out_list_serial_no'), table_name='warehouse_out_list')
    op.drop_index(op.f('ix_warehouse_out_list_master_uid'), table_name='warehouse_out_list')
    op.drop_table('warehouse_out_list')
    op.drop_index(op.f('ix_warehouse_in_list_serial_no'), table_name='warehouse_in_list')
    op.drop_index(op.f('ix_warehouse_in_list_master_uid'), table_name='warehouse_in_list')
    op.drop_table('warehouse_in_list')
    op.drop_index(op.f('ix_warehouse_exchange_list_serial_no'), table_name='warehouse_exchange_list')
    op.drop_index(op.f('ix_warehouse_exchange_list_master_uid'), table_name='warehouse_exchange_list')
    op.drop_table('warehouse_exchange_list')
    # ### end Alembic commands ###
