"""add supplier_id for productsku table

Revision ID: d439834ba5e3
Revises: d51704d93d03
Create Date: 2017-06-22 01:58:56.034359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd439834ba5e3'
down_revision = 'd51704d93d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product_skus', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_skus', type_='foreignkey')
    op.drop_column('product_skus', 'supplier_id')
    # ### end Alembic commands ###
