"""update status to sales log statistics

Revision ID: d45291bf67f9
Revises: d9e2bf72dbbb
Create Date: 2017-12-18 15:19:13.055626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45291bf67f9'
down_revision = 'd9e2bf72dbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_log_statistics', sa.Column('product_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('sales_log_statistics', 'product_id')
    # ### end Alembic commands ###
