"""add trade_content subscribe_services table

Revision ID: d9deb8d9e47b
Revises: e4306c6fc286
Create Date: 2018-04-24 19:39:23.100458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9deb8d9e47b'
down_revision = 'e4306c6fc286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe_services', sa.Column('trade_content', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribe_services', 'trade_content')
    # ### end Alembic commands ###
