"""update status to sales log statistics

Revision ID: d9e2bf72dbbb
Revises: cd9ea43f9999
Create Date: 2017-12-18 11:53:31.723150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e2bf72dbbb'
down_revision = 'cd9ea43f9999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_log_statistics', sa.Column('status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_log_statistics', 'status')
    # ### end Alembic commands ###
