"""remove unique

Revision ID: da22f59cfa2a
Revises: c9d582d0e644
Create Date: 2018-02-05 17:44:50.385415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da22f59cfa2a'
down_revision = 'c9d582d0e644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_abilities_name', table_name='abilities')
    op.create_index(op.f('ix_abilities_name'), 'abilities', ['name'], unique=False)
    op.create_index(op.f('ix_currencies_title'), 'currencies', ['title'], unique=False)
    op.drop_index('title', table_name='currencies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'currencies', ['title'], unique=True)
    op.drop_index(op.f('ix_currencies_title'), table_name='currencies')
    op.drop_index(op.f('ix_abilities_name'), table_name='abilities')
    op.create_index('ix_abilities_name', 'abilities', ['name'], unique=True)
    # ### end Alembic commands ###
