"""add created_at/updated_at for product table

Revision ID: da5734e95149
Revises: 239b23e3fc95
Create Date: 2017-06-20 23:40:12.983700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5734e95149'
down_revision = '239b23e3fc95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('product_skus', sa.Column('updated_at', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_skus_created_at'), 'product_skus', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_skus_created_at'), table_name='product_skus')
    op.drop_column('product_skus', 'updated_at')
    op.drop_column('product_skus', 'created_at')
    # ### end Alembic commands ###
