"""add status wx_template table

Revision ID: dbab97b07896
Revises: f386e73c6415
Create Date: 2018-03-08 13:56:18.022083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbab97b07896'
down_revision = 'f386e73c6415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_templates', sa.Column('status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wx_templates', 'status')
    # ### end Alembic commands ###
