"""add site address banner language

Revision ID: dd53dbf97519
Revises: 231e32bfdae3
Create Date: 2017-11-28 14:45:27.029065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd53dbf97519'
down_revision = '231e32bfdae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banners_master_uid'), 'banners', ['master_uid'], unique=False)
    op.create_table('counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('locale', sa.String(length=255), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.Column('directory', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('sn', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('visit_url', sa.String(length=100), nullable=False),
    sa.Column('site_domain', sa.String(length=100), nullable=True),
    sa.Column('favicon', sa.String(length=100), nullable=True),
    sa.Column('pricing', sa.SmallInteger(), nullable=True),
    sa.Column('domain', sa.SmallInteger(), nullable=True),
    sa.Column('copyright', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_country', sa.Integer(), nullable=True),
    sa.Column('default_language', sa.Integer(), nullable=True),
    sa.Column('default_currency', sa.Integer(), nullable=True),
    sa.Column('unicode', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_domain'),
    sa.UniqueConstraint('visit_url')
    )
    op.create_index(op.f('ix_shops_master_uid'), 'shops', ['master_uid'], unique=False)
    op.create_index(op.f('ix_shops_name'), 'shops', ['name'], unique=False)
    op.create_index(op.f('ix_shops_sn'), 'shops', ['sn'], unique=True)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('country', sa.Integer(), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('street_address', sa.String(length=150), nullable=True),
    sa.Column('street_address_two', sa.String(length=150), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_master_uid'), 'addresses', ['master_uid'], unique=False)
    op.create_table('banner_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('banner_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('image', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banner_id'], ['banners.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_images_master_uid'), 'banner_images', ['master_uid'], unique=False)
    op.create_table('shop_language',
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], )
    )
    op.create_table('shop_seo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_seo')
    op.drop_table('shop_language')
    op.drop_index(op.f('ix_banner_images_master_uid'), table_name='banner_images')
    op.drop_table('banner_images')
    op.drop_index(op.f('ix_addresses_master_uid'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_shops_sn'), table_name='shops')
    op.drop_index(op.f('ix_shops_name'), table_name='shops')
    op.drop_index(op.f('ix_shops_master_uid'), table_name='shops')
    op.drop_table('shops')
    op.drop_table('languages')
    op.drop_table('counters')
    op.drop_index(op.f('ix_banners_master_uid'), table_name='banners')
    op.drop_table('banners')
    # ### end Alembic commands ###
