"""add unique index table

Revision ID: de21a93bf577
Revises: fb9ee4d91ffe
Create Date: 2017-06-26 23:48:42.795412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de21a93bf577'
down_revision = 'fb9ee4d91ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_order_id_sku_id', 'order_items', ['order_id', 'sku_id'])
    op.create_unique_constraint('uix_purchase_sku_id', 'purchase_product', ['purchase_id', 'product_sku_id'])
    op.create_unique_constraint('uix_purchase_sku_id', 'purchase_returned_products', ['purchase_returned_id', 'product_sku_id'])
    op.create_unique_constraint('uix_ex_warehouse_sku_id', 'warehouse_exchange_products', ['exchange_warehouse_id', 'product_sku_id'])
    op.create_unique_constraint('uix_in_warehouse_sku_id', 'warehouse_in_products', ['in_warehouse_id', 'product_sku_id'])
    op.create_unique_constraint('uix_target_id_type', 'warehouse_out_list', ['target_id', 'target_type'])
    op.create_unique_constraint('uix_out_warehouse_sku_id', 'warehouse_out_products', ['out_warehouse_id', 'product_sku_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_out_warehouse_sku_id', 'warehouse_out_products', type_='unique')
    op.drop_constraint('uix_target_id_type', 'warehouse_out_list', type_='unique')
    op.drop_constraint('uix_in_warehouse_sku_id', 'warehouse_in_products', type_='unique')
    op.drop_constraint('uix_ex_warehouse_sku_id', 'warehouse_exchange_products', type_='unique')
    op.drop_constraint('uix_purchase_sku_id', 'purchase_returned_products', type_='unique')
    op.drop_constraint('uix_purchase_sku_id', 'purchase_product', type_='unique')
    op.drop_constraint('uix_order_id_sku_id', 'order_items', type_='unique')
    # ### end Alembic commands ###
