"""add sku_serial_no for stock_history table

Revision ID: deb2e8aab4fc
Revises: 97aeb14dfa8f
Create Date: 2017-07-09 22:51:49.181427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb2e8aab4fc'
down_revision = '97aeb14dfa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_stock_history', sa.Column('sku_serial_no', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_warehouse_stock_history_sku_serial_no'), 'warehouse_stock_history', ['sku_serial_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_stock_history_sku_serial_no'), table_name='warehouse_stock_history')
    op.drop_column('warehouse_stock_history', 'sku_serial_no')
    # ### end Alembic commands ###
