"""update warehouse stock history table

Revision ID: deb58845fbb5
Revises: a0f55b5a8ee5
Create Date: 2017-06-28 11:49:39.592518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb58845fbb5'
down_revision = 'a0f55b5a8ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_stock_history', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('warehouse_stock_history', sa.Column('updated_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse_stock_history', 'updated_at')
    op.drop_column('warehouse_stock_history', 'created_at')
    # ### end Alembic commands ###
