"""add finance table

Revision ID: dfc15b65eeb2
Revises: 4fa22c916834
Create Date: 2017-06-22 19:35:34.291068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc15b65eeb2'
down_revision = '4fa22c916834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('account', sa.String(length=30), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_master_uid'), 'invoices', ['master_uid'], unique=False)
    op.create_table('transact_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('pay_account_id', sa.Integer(), nullable=True),
    sa.Column('transact_user', sa.String(length=30), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.SmallInteger(), nullable=True),
    sa.Column('payed_at', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pay_account_id'], ['pay_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transact_details_created_at'), 'transact_details', ['created_at'], unique=False)
    op.create_index(op.f('ix_transact_details_serial_no'), 'transact_details', ['serial_no'], unique=True)
    op.create_index(op.f('ix_transact_details_transact_user'), 'transact_details', ['transact_user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transact_details_transact_user'), table_name='transact_details')
    op.drop_index(op.f('ix_transact_details_serial_no'), table_name='transact_details')
    op.drop_index(op.f('ix_transact_details_created_at'), table_name='transact_details')
    op.drop_table('transact_details')
    op.drop_index(op.f('ix_invoices_master_uid'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('pay_accounts')
    # ### end Alembic commands ###
