"""add sku_serial_no for order_item table

Revision ID: e18459cd039b
Revises: 2e87c15d0fdd
Create Date: 2017-07-10 16:52:38.886140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18459cd039b'
down_revision = '2e87c15d0fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('sku_serial_no', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_order_items_sku_serial_no'), 'order_items', ['sku_serial_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_sku_serial_no'), table_name='order_items')
    op.drop_column('order_items', 'sku_serial_no')
    # ### end Alembic commands ###
