"""modify field express/shipper table

Revision ID: e779d9aa6335
Revises: f47893579171
Create Date: 2017-07-02 00:39:59.866169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e779d9aa6335'
down_revision = 'f47893579171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expresses', 'contact_phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expresses', sa.Column('contact_phone', mysql.VARCHAR(length=11), nullable=True))
    # ### end Alembic commands ###
