"""add wx_templates table

Revision ID: e7993bbd0958
Revises: fb85eb6ae589
Create Date: 2018-03-01 01:03:48.329156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7993bbd0958'
down_revision = 'fb85eb6ae589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('attachment', sa.String(length=200), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cover_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wx_templates_name'), 'wx_templates', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_templates_name'), table_name='wx_templates')
    op.drop_table('wx_templates')
    # ### end Alembic commands ###
