"""add locale for user table

Revision ID: e8a6ef39891c
Revises: c3d7eeeb8807
Create Date: 2017-06-15 11:13:59.812848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a6ef39891c'
down_revision = 'c3d7eeeb8807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    # ### end Alembic commands ###
