"""init tables

Revision ID: eb4cc5c550a5
Revises: 
Create Date: 2017-12-26 23:05:16.373393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4cc5c550a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abilities_name'), 'abilities', ['name'], unique=True)
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banners_master_uid'), 'banners', ['master_uid'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('sess_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('recurring_id', sa.Integer(), nullable=True),
    sa.Column('sku_rid', sa.String(length=12), nullable=True),
    sa.Column('option', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_master_uid'), 'carts', ['master_uid'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_uid', 'name', name='uix_master_uid_name')
    )
    op.create_index(op.f('ix_categories_master_uid'), 'categories', ['master_uid'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index('ix_master_uid_pid', 'categories', ['master_uid', 'pid'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('app_key', sa.String(length=20), nullable=False),
    sa.Column('app_secret', sa.String(length=40), nullable=False),
    sa.Column('limit_times', sa.Integer(), nullable=True),
    sa.Column('receive_url', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.String(length=140), nullable=True),
    sa.Column('white_list', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_name', sa.String(length=128), nullable=False),
    sa.Column('en_name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('code2', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_cn_name'), 'countries', ['cn_name'], unique=False)
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=False)
    op.create_index(op.f('ix_countries_en_name'), 'countries', ['en_name'], unique=False)
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('symbol_left', sa.String(length=12), nullable=True),
    sa.Column('symbol_right', sa.String(length=12), nullable=True),
    sa.Column('decimal_place', sa.String(length=1), nullable=False),
    sa.Column('value', sa.Float(precision=15, asdecimal=8), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('customer_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('top', sa.SmallInteger(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directories_master_uid'), 'directories', ['master_uid'], unique=False)
    op.create_index(op.f('ix_directories_name'), 'directories', ['name'], unique=False)
    op.create_table('discount_templets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('default_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('contact_name', sa.String(length=16), nullable=False),
    sa.Column('contact_mobile', sa.String(length=11), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('customer_name', sa.String(length=32), nullable=True),
    sa.Column('customer_pwd', sa.String(length=100), nullable=True),
    sa.Column('send_site', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expresses_code'), 'expresses', ['code'], unique=False)
    op.create_index(op.f('ix_expresses_master_uid'), 'expresses', ['master_uid'], unique=False)
    op.create_index(op.f('ix_expresses_name'), 'expresses', ['name'], unique=False)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('locale', sa.String(length=255), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.Column('directory', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('master_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('time', sa.String(length=8), nullable=False),
    sa.Column('income_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('income_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_uid', 'type', 'time')
    )
    op.create_index(op.f('ix_master_statistics_master_uid'), 'master_statistics', ['master_uid'], unique=False)
    op.create_table('product_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_master_uid'), 'roles', ['master_uid'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('sn', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('visit_url', sa.String(length=100), nullable=False),
    sa.Column('site_domain', sa.String(length=100), nullable=True),
    sa.Column('favicon', sa.String(length=100), nullable=True),
    sa.Column('pricing', sa.SmallInteger(), nullable=True),
    sa.Column('domain', sa.SmallInteger(), nullable=True),
    sa.Column('copyright', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_country', sa.Integer(), nullable=True),
    sa.Column('default_language', sa.Integer(), nullable=True),
    sa.Column('default_currency', sa.Integer(), nullable=True),
    sa.Column('unicode', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_domain'),
    sa.UniqueConstraint('visit_url')
    )
    op.create_index(op.f('ix_shops_master_uid'), 'shops', ['master_uid'], unique=False)
    op.create_index(op.f('ix_shops_name'), 'shops', ['name'], unique=False)
    op.create_index(op.f('ix_shops_sn'), 'shops', ['sn'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=1), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('contact_name', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('time_limit', sa.String(length=50), nullable=True),
    sa.Column('business_scope', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_created_at'), 'suppliers', ['created_at'], unique=False)
    op.create_index(op.f('ix_suppliers_full_name'), 'suppliers', ['full_name'], unique=False)
    op.create_index(op.f('ix_suppliers_master_uid'), 'suppliers', ['master_uid'], unique=False)
    op.create_index(op.f('ix_suppliers_short_name'), 'suppliers', ['short_name'], unique=False)
    op.create_index(op.f('ix_suppliers_type'), 'suppliers', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.String(length=11), nullable=True),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('is_setting', sa.Boolean(), nullable=True),
    sa.Column('id_type', sa.SmallInteger(), nullable=True),
    sa.Column('locale', sa.String(length=4), nullable=True),
    sa.Column('language', sa.String(length=4), nullable=True),
    sa.Column('time_zone', sa.String(length=20), nullable=False),
    sa.Column('disabled_at', sa.Integer(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_master_uid'), 'users', ['master_uid'], unique=False)
    op.create_index(op.f('ix_users_sn'), 'users', ['sn'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('warehouse_exchange_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('out_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('in_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('out_in_status', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_user_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_exchange_list_master_uid'), 'warehouse_exchange_list', ['master_uid'], unique=False)
    op.create_index(op.f('ix_warehouse_exchange_list_serial_no'), 'warehouse_exchange_list', ['serial_no'], unique=True)
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlist_master_uid'), 'wishlist', ['master_uid'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('country', sa.Integer(), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('street_address', sa.String(length=150), nullable=True),
    sa.Column('street_address_two', sa.String(length=150), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_master_uid'), 'addresses', ['master_uid'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('directory_id', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mime', sa.String(length=64), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('state', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['directory_id'], ['directories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_index(op.f('ix_assets_master_uid'), 'assets', ['master_uid'], unique=False)
    op.create_table('banner_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('banner_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('image', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banner_id'], ['banners.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_images_master_uid'), 'banner_images', ['master_uid'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.String(length=9), nullable=True),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('features', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_id', sa.Integer(), nullable=True),
    sa.Column('banner_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_created_at'), 'brands', ['created_at'], unique=False)
    op.create_index(op.f('ix_brands_master_uid'), 'brands', ['master_uid'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_index(op.f('ix_brands_sn'), 'brands', ['sn'], unique=True)
    op.create_table('categories_paths',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'path_id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('sn', sa.String(length=20), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('street_address', sa.String(length=150), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('qq', sa.String(length=50), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['customer_grades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount_templet_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('discount_templet_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discount_templet_id'], ['discount_templets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_abilities',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('ability_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('shop_language',
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], )
    )
    op.create_table('shop_seo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.Column('company_abbr', sa.String(length=10), nullable=True),
    sa.Column('locale', sa.String(length=4), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_company_name'), 'sites', ['company_name'], unique=True)
    op.create_index(op.f('ix_sites_master_uid'), 'sites', ['master_uid'], unique=True)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('serial_no', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.Integer(), nullable=True),
    sa.Column('authorize_expired_at', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=100), nullable=True),
    sa.Column('refresh_token', sa.String(length=100), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.create_index(op.f('ix_stores_serial_no'), 'stores', ['serial_no'], unique=True)
    op.create_table('supply_relevance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('sku_count', sa.Integer(), nullable=True),
    sa.Column('purchase_times', sa.Integer(), nullable=True),
    sa.Column('purchase_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('latest_trade_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_uid', 'supplier_id', name='uix_supply_master_uid_supplier_id')
    )
    op.create_index(op.f('ix_supply_relevance_created_at'), 'supply_relevance', ['created_at'], unique=False)
    op.create_index(op.f('ix_supply_relevance_master_uid'), 'supply_relevance', ['master_uid'], unique=False)
    op.create_table('users_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('en_address', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('qq', sa.String(length=32), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pay_mode', sa.SmallInteger(), nullable=True),
    sa.Column('sale_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_services_name'), 'app_services', ['name'], unique=False)
    op.create_index(op.f('ix_app_services_serial_no'), 'app_services', ['serial_no'], unique=True)
    op.create_table('customer_distribute_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_packet_id', sa.Integer(), nullable=True),
    sa.Column('discount_templet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['discount_templet_id'], ['discount_templets.id'], ),
    sa.ForeignKeyConstraint(['product_packet_id'], ['product_packets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('outside_target_id', sa.String(length=32), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('pay_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('freight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('express_id', sa.Integer(), nullable=True),
    sa.Column('express_no', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('invoice_type', sa.SmallInteger(), nullable=True),
    sa.Column('buyer_name', sa.String(length=50), nullable=False),
    sa.Column('buyer_tel', sa.String(length=20), nullable=True),
    sa.Column('buyer_phone', sa.String(length=20), nullable=True),
    sa.Column('buyer_zipcode', sa.String(length=16), nullable=True),
    sa.Column('buyer_address', sa.String(length=200), nullable=True),
    sa.Column('buyer_country', sa.String(length=50), nullable=True),
    sa.Column('buyer_province', sa.String(length=50), nullable=True),
    sa.Column('buyer_city', sa.String(length=50), nullable=True),
    sa.Column('buyer_area', sa.String(length=50), nullable=True),
    sa.Column('buyer_remark', sa.String(length=250), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('suspend', sa.Boolean(), nullable=True),
    sa.Column('expired_time', sa.Integer(), nullable=True),
    sa.Column('from_client', sa.SmallInteger(), nullable=True),
    sa.Column('affiliate_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.Integer(), nullable=True),
    sa.Column('payed_at', sa.Integer(), nullable=True),
    sa.Column('express_at', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.Integer(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('related_rid', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_buyer_name'), 'orders', ['buyer_name'], unique=False)
    op.create_index(op.f('ix_orders_buyer_phone'), 'orders', ['buyer_phone'], unique=False)
    op.create_index(op.f('ix_orders_buyer_tel'), 'orders', ['buyer_tel'], unique=False)
    op.create_index(op.f('ix_orders_master_uid'), 'orders', ['master_uid'], unique=False)
    op.create_index(op.f('ix_orders_outside_target_id'), 'orders', ['outside_target_id'], unique=False)
    op.create_index(op.f('ix_orders_serial_no'), 'orders', ['serial_no'], unique=True)
    op.create_table('pay_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('account', sa.String(length=30), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=12), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('id_code', sa.String(length=16), nullable=True),
    sa.Column('region_id', sa.SmallInteger(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('s_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('s_length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('s_width', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('s_height', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('from_url', sa.String(length=255), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['cover_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_master_uid'), 'products', ['master_uid'], unique=False)
    op.create_index(op.f('ix_products_serial_no'), 'products', ['serial_no'], unique=True)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=16), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('sku_count', sa.Integer(), nullable=True),
    sa.Column('quantity_sum', sa.Integer(), nullable=True),
    sa.Column('in_quantity', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('freight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extra_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('express_name', sa.String(length=30), nullable=True),
    sa.Column('express_no', sa.String(length=255), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('arrival_at', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('payed', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_master_uid'), 'purchases', ['master_uid'], unique=False)
    op.create_index(op.f('ix_purchases_serial_no'), 'purchases', ['serial_no'], unique=True)
    op.create_table('shippers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('from_city', sa.String(length=32), nullable=False),
    sa.Column('province', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shippers_from_city'), 'shippers', ['from_city'], unique=False)
    op.create_index(op.f('ix_shippers_master_uid'), 'shippers', ['master_uid'], unique=False)
    op.create_table('store_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('time', sa.String(length=8), nullable=False),
    sa.Column('income_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('income_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'type', 'time')
    )
    op.create_index(op.f('ix_store_statistics_master_uid'), 'store_statistics', ['master_uid'], unique=False)
    op.create_index(op.f('ix_store_statistics_store_id'), 'store_statistics', ['store_id'], unique=False)
    op.create_index('master_uid', 'store_statistics', ['time', 'store_id'], unique=False)
    op.create_table('warehouse_in_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('target_serial_no', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.SmallInteger(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('in_status', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_target_serial_type', 'warehouse_in_list', ['target_serial_no', 'target_type'], unique=False)
    op.create_index(op.f('ix_warehouse_in_list_master_uid'), 'warehouse_in_list', ['master_uid'], unique=False)
    op.create_index(op.f('ix_warehouse_in_list_serial_no'), 'warehouse_in_list', ['serial_no'], unique=True)
    op.create_index(op.f('ix_warehouse_in_list_target_serial_no'), 'warehouse_in_list', ['target_serial_no'], unique=False)
    op.create_table('warehouse_out_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('target_serial_no', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.SmallInteger(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('out_quantity', sa.Integer(), nullable=True),
    sa.Column('out_status', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_target_serial_type', 'warehouse_out_list', ['target_serial_no', 'target_type'], unique=False)
    op.create_index(op.f('ix_warehouse_out_list_master_uid'), 'warehouse_out_list', ['master_uid'], unique=False)
    op.create_index(op.f('ix_warehouse_out_list_serial_no'), 'warehouse_out_list', ['serial_no'], unique=True)
    op.create_index(op.f('ix_warehouse_out_list_target_serial_no'), 'warehouse_out_list', ['target_serial_no'], unique=False)
    op.create_table('warehouse_shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_shelves_name'), 'warehouse_shelves', ['name'], unique=False)
    op.create_table('categories_products',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    op.create_table('customs_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('dangerous_goods', sa.String(length=1), nullable=True),
    sa.Column('local_name', sa.String(length=100), nullable=False),
    sa.Column('en_name', sa.String(length=100), nullable=False),
    sa.Column('s_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('customs_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customs_declarations_created_at'), 'customs_declarations', ['created_at'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_master_uid'), 'invoices', ['master_uid'], unique=False)
    op.create_table('packet_products',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_packet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_packet_id'], ['product_packets.id'], )
    )
    op.create_table('product_skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=12), nullable=False),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('id_code', sa.String(length=16), nullable=True),
    sa.Column('s_model', sa.String(length=64), nullable=False),
    sa.Column('s_color', sa.String(length=32), nullable=True),
    sa.Column('s_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('region_id', sa.SmallInteger(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('outside_serial_no', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cover_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_skus_created_at'), 'product_skus', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_skus_master_uid'), 'product_skus', ['master_uid'], unique=False)
    op.create_index(op.f('ix_product_skus_outside_serial_no'), 'product_skus', ['outside_serial_no'], unique=False)
    op.create_index(op.f('ix_product_skus_serial_no'), 'product_skus', ['serial_no'], unique=True)
    op.create_table('purchase_returned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('outed_quantity', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_user_id', sa.Integer(), nullable=True),
    sa.Column('outed_status', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_returned_serial_no'), 'purchase_returned', ['serial_no'], unique=True)
    op.create_table('service_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pay_mode', sa.SmallInteger(), nullable=True),
    sa.Column('discount_money', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ordered_at', sa.Integer(), nullable=True),
    sa.Column('ordered_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['app_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribe_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('ordered_at', sa.Integer(), nullable=True),
    sa.Column('expired_at', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['app_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transact_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('pay_account_id', sa.Integer(), nullable=True),
    sa.Column('transact_user', sa.String(length=30), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.SmallInteger(), nullable=True),
    sa.Column('payed_at', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pay_account_id'], ['pay_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'target_type', name='uix_target_id_type')
    )
    op.create_index(op.f('ix_transact_details_created_at'), 'transact_details', ['created_at'], unique=False)
    op.create_index(op.f('ix_transact_details_serial_no'), 'transact_details', ['serial_no'], unique=True)
    op.create_index(op.f('ix_transact_details_transact_user'), 'transact_details', ['transact_user'], unique=False)
    op.create_table('day_sku_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku_id', 'time')
    )
    op.create_index(op.f('ix_day_sku_statistics_category_id'), 'day_sku_statistics', ['category_id'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_master_uid'), 'day_sku_statistics', ['master_uid'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_product_id'), 'day_sku_statistics', ['product_id'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_sku_id'), 'day_sku_statistics', ['sku_id'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_sku_serial_no'), 'day_sku_statistics', ['sku_serial_no'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_store_id'), 'day_sku_statistics', ['store_id'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_supplier_id'), 'day_sku_statistics', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_day_sku_statistics_time'), 'day_sku_statistics', ['time'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_serial_no', sa.String(length=20), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('deal_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'sku_id', name='uix_order_id_sku_id')
    )
    op.create_index(op.f('ix_order_items_order_serial_no'), 'order_items', ['order_serial_no'], unique=False)
    op.create_index(op.f('ix_order_items_sku_serial_no'), 'order_items', ['sku_serial_no'], unique=False)
    op.create_table('product_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('time', sa.String(length=8), nullable=False),
    sa.Column('time_type', sa.SmallInteger(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('income_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('income_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_yoy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_mom', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku_id', 'time', 'time_type')
    )
    op.create_index(op.f('ix_product_statistics_master_uid'), 'product_statistics', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    op.create_index(op.f('ix_product_statistics_sku_serial_no'), 'product_statistics', ['sku_serial_no'], unique=False)
    op.create_index(op.f('ix_product_statistics_store_id'), 'product_statistics', ['store_id'], unique=False)
    op.create_table('product_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('product_sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_shelve_id', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('presale_count', sa.Integer(), nullable=True),
    sa.Column('saled_count', sa.Integer(), nullable=True),
    sa.Column('defective_count', sa.Integer(), nullable=True),
    sa.Column('returned_count', sa.Integer(), nullable=True),
    sa.Column('manual_count', sa.Integer(), nullable=True),
    sa.Column('min_count', sa.Integer(), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['warehouse_shelve_id'], ['warehouse_shelves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_stocks_created_at'), 'product_stocks', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_stocks_master_uid'), 'product_stocks', ['master_uid'], unique=False)
    op.create_index(op.f('ix_product_stocks_product_sku_id'), 'product_stocks', ['product_sku_id'], unique=False)
    op.create_index(op.f('ix_product_stocks_sku_serial_no'), 'product_stocks', ['sku_serial_no'], unique=False)
    op.create_index(op.f('ix_product_stocks_warehouse_id'), 'product_stocks', ['warehouse_id'], unique=False)
    op.create_table('purchase_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('product_sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('in_quantity', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('freight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id', 'product_sku_id', name='uix_purchase_sku_id')
    )
    op.create_index(op.f('ix_purchase_product_sku_serial_no'), 'purchase_product', ['sku_serial_no'], unique=False)
    op.create_table('purchase_returned_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_returned_id', sa.Integer(), nullable=True),
    sa.Column('product_sku_id', sa.Integer(), nullable=True),
    sa.Column('returned_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('returned_quantity', sa.Integer(), nullable=True),
    sa.Column('outed_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['purchase_returned_id'], ['purchase_returned.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_returned_id', 'product_sku_id', name='uix_purchase_sku_id')
    )
    op.create_table('sales_log_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('deal_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('create_at', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_log_statistics_create_at'), 'sales_log_statistics', ['create_at'], unique=False)
    op.create_index(op.f('ix_sales_log_statistics_master_uid'), 'sales_log_statistics', ['master_uid'], unique=False)
    op.create_index(op.f('ix_sales_log_statistics_order_id'), 'sales_log_statistics', ['order_id'], unique=False)
    op.create_index(op.f('ix_sales_log_statistics_product_id'), 'sales_log_statistics', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_log_statistics_sku_serial_no'), 'sales_log_statistics', ['sku_serial_no'], unique=False)
    op.create_index(op.f('ix_sales_log_statistics_store_id'), 'sales_log_statistics', ['store_id'], unique=False)
    op.create_table('warehouse_exchange_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('product_sku_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_warehouse_id'], ['warehouse_exchange_list.id'], ),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_warehouse_id', 'product_sku_id', name='uix_ex_warehouse_sku_id')
    )
    op.create_table('warehouse_stock_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_shelve_id', sa.Integer(), nullable=True),
    sa.Column('product_sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_serial_no', sa.String(length=12), nullable=False),
    sa.Column('serial_no', sa.String(length=20), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=True),
    sa.Column('original_quantity', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('current_quantity', sa.Integer(), nullable=True),
    sa.Column('ori_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['warehouse_shelve_id'], ['warehouse_shelves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_stock_history_master_uid'), 'warehouse_stock_history', ['master_uid'], unique=False)
    op.create_index(op.f('ix_warehouse_stock_history_serial_no'), 'warehouse_stock_history', ['serial_no'], unique=False)
    op.create_index(op.f('ix_warehouse_stock_history_sku_serial_no'), 'warehouse_stock_history', ['sku_serial_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_stock_history_sku_serial_no'), table_name='warehouse_stock_history')
    op.drop_index(op.f('ix_warehouse_stock_history_serial_no'), table_name='warehouse_stock_history')
    op.drop_index(op.f('ix_warehouse_stock_history_master_uid'), table_name='warehouse_stock_history')
    op.drop_table('warehouse_stock_history')
    op.drop_table('warehouse_exchange_products')
    op.drop_index(op.f('ix_sales_log_statistics_store_id'), table_name='sales_log_statistics')
    op.drop_index(op.f('ix_sales_log_statistics_sku_serial_no'), table_name='sales_log_statistics')
    op.drop_index(op.f('ix_sales_log_statistics_product_id'), table_name='sales_log_statistics')
    op.drop_index(op.f('ix_sales_log_statistics_order_id'), table_name='sales_log_statistics')
    op.drop_index(op.f('ix_sales_log_statistics_master_uid'), table_name='sales_log_statistics')
    op.drop_index(op.f('ix_sales_log_statistics_create_at'), table_name='sales_log_statistics')
    op.drop_table('sales_log_statistics')
    op.drop_table('purchase_returned_products')
    op.drop_index(op.f('ix_purchase_product_sku_serial_no'), table_name='purchase_product')
    op.drop_table('purchase_product')
    op.drop_index(op.f('ix_product_stocks_warehouse_id'), table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_sku_serial_no'), table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_product_sku_id'), table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_master_uid'), table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_created_at'), table_name='product_stocks')
    op.drop_table('product_stocks')
    op.drop_index(op.f('ix_product_statistics_store_id'), table_name='product_statistics')
    op.drop_index(op.f('ix_product_statistics_sku_serial_no'), table_name='product_statistics')
    op.drop_index(op.f('ix_product_statistics_master_uid'), table_name='product_statistics')
    op.drop_table('product_statistics')
    op.drop_index(op.f('ix_order_items_sku_serial_no'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_serial_no'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_day_sku_statistics_time'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_supplier_id'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_store_id'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_sku_serial_no'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_sku_id'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_product_id'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_master_uid'), table_name='day_sku_statistics')
    op.drop_index(op.f('ix_day_sku_statistics_category_id'), table_name='day_sku_statistics')
    op.drop_table('day_sku_statistics')
    op.drop_index(op.f('ix_transact_details_transact_user'), table_name='transact_details')
    op.drop_index(op.f('ix_transact_details_serial_no'), table_name='transact_details')
    op.drop_index(op.f('ix_transact_details_created_at'), table_name='transact_details')
    op.drop_table('transact_details')
    op.drop_table('subscribe_services')
    op.drop_table('service_transactions')
    op.drop_index(op.f('ix_purchase_returned_serial_no'), table_name='purchase_returned')
    op.drop_table('purchase_returned')
    op.drop_index(op.f('ix_product_skus_serial_no'), table_name='product_skus')
    op.drop_index(op.f('ix_product_skus_outside_serial_no'), table_name='product_skus')
    op.drop_index(op.f('ix_product_skus_master_uid'), table_name='product_skus')
    op.drop_index(op.f('ix_product_skus_created_at'), table_name='product_skus')
    op.drop_table('product_skus')
    op.drop_table('packet_products')
    op.drop_index(op.f('ix_invoices_master_uid'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_customs_declarations_created_at'), table_name='customs_declarations')
    op.drop_table('customs_declarations')
    op.drop_table('categories_products')
    op.drop_index(op.f('ix_warehouse_shelves_name'), table_name='warehouse_shelves')
    op.drop_table('warehouse_shelves')
    op.drop_index(op.f('ix_warehouse_out_list_target_serial_no'), table_name='warehouse_out_list')
    op.drop_index(op.f('ix_warehouse_out_list_serial_no'), table_name='warehouse_out_list')
    op.drop_index(op.f('ix_warehouse_out_list_master_uid'), table_name='warehouse_out_list')
    op.drop_index('ix_target_serial_type', table_name='warehouse_out_list')
    op.drop_table('warehouse_out_list')
    op.drop_index(op.f('ix_warehouse_in_list_target_serial_no'), table_name='warehouse_in_list')
    op.drop_index(op.f('ix_warehouse_in_list_serial_no'), table_name='warehouse_in_list')
    op.drop_index(op.f('ix_warehouse_in_list_master_uid'), table_name='warehouse_in_list')
    op.drop_index('ix_target_serial_type', table_name='warehouse_in_list')
    op.drop_table('warehouse_in_list')
    op.drop_index('master_uid', table_name='store_statistics')
    op.drop_index(op.f('ix_store_statistics_store_id'), table_name='store_statistics')
    op.drop_index(op.f('ix_store_statistics_master_uid'), table_name='store_statistics')
    op.drop_table('store_statistics')
    op.drop_index(op.f('ix_shippers_master_uid'), table_name='shippers')
    op.drop_index(op.f('ix_shippers_from_city'), table_name='shippers')
    op.drop_table('shippers')
    op.drop_index(op.f('ix_purchases_serial_no'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_master_uid'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_products_serial_no'), table_name='products')
    op.drop_index(op.f('ix_products_master_uid'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_table('products')
    op.drop_table('pay_accounts')
    op.drop_index(op.f('ix_orders_serial_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_outside_target_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_master_uid'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_tel'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_phone'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_name'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('customer_distribute_packets')
    op.drop_index(op.f('ix_app_services_serial_no'), table_name='app_services')
    op.drop_index(op.f('ix_app_services_name'), table_name='app_services')
    op.drop_table('app_services')
    op.drop_table('warehouses')
    op.drop_table('users_roles')
    op.drop_index(op.f('ix_supply_relevance_master_uid'), table_name='supply_relevance')
    op.drop_index(op.f('ix_supply_relevance_created_at'), table_name='supply_relevance')
    op.drop_table('supply_relevance')
    op.drop_index(op.f('ix_stores_serial_no'), table_name='stores')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_sites_master_uid'), table_name='sites')
    op.drop_index(op.f('ix_sites_company_name'), table_name='sites')
    op.drop_table('sites')
    op.drop_table('shop_seo')
    op.drop_table('shop_language')
    op.drop_table('roles_abilities')
    op.drop_table('discount_templet_items')
    op.drop_table('customers')
    op.drop_table('categories_paths')
    op.drop_index(op.f('ix_brands_sn'), table_name='brands')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_master_uid'), table_name='brands')
    op.drop_index(op.f('ix_brands_created_at'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_banner_images_master_uid'), table_name='banner_images')
    op.drop_table('banner_images')
    op.drop_index(op.f('ix_assets_master_uid'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_addresses_master_uid'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_wishlist_master_uid'), table_name='wishlist')
    op.drop_table('wishlist')
    op.drop_index(op.f('ix_warehouse_exchange_list_serial_no'), table_name='warehouse_exchange_list')
    op.drop_index(op.f('ix_warehouse_exchange_list_master_uid'), table_name='warehouse_exchange_list')
    op.drop_table('warehouse_exchange_list')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_sn'), table_name='users')
    op.drop_index(op.f('ix_users_master_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_type'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_short_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_master_uid'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_full_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_created_at'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_shops_sn'), table_name='shops')
    op.drop_index(op.f('ix_shops_name'), table_name='shops')
    op.drop_index(op.f('ix_shops_master_uid'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_master_uid'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('reminders')
    op.drop_table('product_packets')
    op.drop_index(op.f('ix_master_statistics_master_uid'), table_name='master_statistics')
    op.drop_table('master_statistics')
    op.drop_table('languages')
    op.drop_index(op.f('ix_expresses_name'), table_name='expresses')
    op.drop_index(op.f('ix_expresses_master_uid'), table_name='expresses')
    op.drop_index(op.f('ix_expresses_code'), table_name='expresses')
    op.drop_table('expresses')
    op.drop_table('discount_templets')
    op.drop_index(op.f('ix_directories_name'), table_name='directories')
    op.drop_index(op.f('ix_directories_master_uid'), table_name='directories')
    op.drop_table('directories')
    op.drop_table('customer_grades')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_countries_en_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_index(op.f('ix_countries_cn_name'), table_name='countries')
    op.drop_table('countries')
    op.drop_table('counters')
    op.drop_table('clients')
    op.drop_index('ix_master_uid_pid', table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_master_uid'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_carts_master_uid'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_banners_master_uid'), table_name='banners')
    op.drop_table('banners')
    op.drop_index(op.f('ix_abilities_name'), table_name='abilities')
    op.drop_table('abilities')
    # ### end Alembic commands ###
