"""add type for order table

Revision ID: ef933845b398
Revises: 15bf3259922d
Create Date: 2017-08-26 21:33:22.240631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef933845b398'
down_revision = '15bf3259922d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'type')
    # ### end Alembic commands ###
