"""add user_id search_history table

Revision ID: f386e73c6415
Revises: 211609027f83
Create Date: 2018-03-07 14:43:22.828543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f386e73c6415'
down_revision = '211609027f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_column('search_history', 'user_id')
    # ### end Alembic commands ###
