"""add master_uid for role table

Revision ID: f43124864055
Revises: bbfc02507791
Create Date: 2017-07-03 01:22:55.977481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43124864055'
down_revision = 'bbfc02507791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('master_uid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_master_uid'), 'roles', ['master_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_master_uid'), table_name='roles')
    op.drop_column('roles', 'master_uid')
    # ### end Alembic commands ###
