"""modify field express/shipper table

Revision ID: f46c5669750f
Revises: e779d9aa6335
Create Date: 2017-07-02 00:40:11.650980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46c5669750f'
down_revision = 'e779d9aa6335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expresses', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expresses', 'contact_phone')
    # ### end Alembic commands ###
