"""modify field express/shipper table

Revision ID: f47893579171
Revises: cc1da38474ce
Create Date: 2017-07-02 00:25:52.983989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f47893579171'
down_revision = 'cc1da38474ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expresses', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('expresses', sa.Column('updated_at', sa.Integer(), nullable=True))
    op.drop_index('ix_expresses_company', table_name='expresses')
    op.drop_column('expresses', 'company')
    op.add_column('shippers', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('shippers', sa.Column('updated_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shippers', 'updated_at')
    op.drop_column('shippers', 'created_at')
    op.add_column('expresses', sa.Column('company', mysql.VARCHAR(length=2), nullable=False))
    op.create_index('ix_expresses_company', 'expresses', ['company'], unique=False)
    op.drop_column('expresses', 'updated_at')
    op.drop_column('expresses', 'created_at')
    # ### end Alembic commands ###
