"""update in_out_warehouse index table

Revision ID: f6f76963b293
Revises: 44d2e1429a2c
Create Date: 2017-06-27 22:00:05.889485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f76963b293'
down_revision = '44d2e1429a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_target_id_type', 'warehouse_in_list', ['target_id', 'target_type'], unique=False)
    op.create_foreign_key(None, 'warehouse_in_list', 'warehouses', ['warehouse_id'], ['id'])
    op.create_index('ix_target_id_type', 'warehouse_out_list', ['target_id', 'target_type'], unique=False)
    op.create_foreign_key(None, 'warehouse_out_list', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse_out_list', type_='foreignkey')
    op.drop_index('ix_target_id_type', table_name='warehouse_out_list')
    op.drop_constraint(None, 'warehouse_in_list', type_='foreignkey')
    op.drop_index('ix_target_id_type', table_name='warehouse_in_list')
    # ### end Alembic commands ###
