"""add wx_payments table

Revision ID: fb85eb6ae589
Revises: 11981843f486
Create Date: 2018-03-01 00:45:19.873901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb85eb6ae589'
down_revision = '11981843f486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('auth_app_id', sa.String(length=32), nullable=False),
    sa.Column('mch_id', sa.String(length=16), nullable=False),
    sa.Column('mch_key', sa.String(length=64), nullable=False),
    sa.Column('ssl_key', sa.String(length=100), nullable=True),
    sa.Column('ssl_cert', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wx_payments_auth_app_id'), 'wx_payments', ['auth_app_id'], unique=False)
    op.create_index(op.f('ix_wx_payments_master_uid'), 'wx_payments', ['master_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_payments_master_uid'), table_name='wx_payments')
    op.drop_index(op.f('ix_wx_payments_auth_app_id'), table_name='wx_payments')
    op.drop_table('wx_payments')
    # ### end Alembic commands ###
