"""add unique index table

Revision ID: fb9ee4d91ffe
Revises: dfc15b65eeb2
Create Date: 2017-06-26 23:39:04.463709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9ee4d91ffe'
down_revision = 'dfc15b65eeb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_target_id_type', 'transact_details', ['target_id', 'target_type'])
    op.create_unique_constraint('uix_target_id_type', 'warehouse_in_list', ['target_id', 'target_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_target_id_type', 'warehouse_in_list', type_='unique')
    op.drop_constraint('uix_target_id_type', 'transact_details', type_='unique')
    # ### end Alembic commands ###
