"""add status banner

Revision ID: fbb61dfd3ab5
Revises: bc44ec94f137
Create Date: 2018-01-02 01:57:26.576566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb61dfd3ab5'
down_revision = 'bc44ec94f137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_images', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('banner_images', sa.Column('type', sa.SmallInteger(), nullable=True))
    op.drop_index('ix_product_statistics_master_uid', table_name='product_statistics')
    op.create_index(op.f('ix_product_statistics_master_uid'), 'product_statistics', ['master_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_statistics_master_uid'), table_name='product_statistics')
    op.create_index('ix_product_statistics_master_uid', 'product_statistics', ['master_uid', 'sku_id', 'time', 'store_id'], unique=False)
    op.drop_column('banner_images', 'type')
    op.drop_column('banner_images', 'status')
    # ### end Alembic commands ###
