"""add tester wx_mini_app table

Revision ID: ff8d961af1ba
Revises: dbab97b07896
Create Date: 2018-03-08 17:25:20.688773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8d961af1ba'
down_revision = 'dbab97b07896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('auth_app_id', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.String(length=32), nullable=True),
    sa.Column('audit_id', sa.String(length=16), nullable=True),
    sa.Column('audit_status', sa.String(length=32), nullable=True),
    sa.Column('audit_at', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('user_version', sa.String(length=30), nullable=True),
    sa.Column('user_desc', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wx_versions_auth_app_id'), 'wx_versions', ['auth_app_id'], unique=False)
    op.create_index(op.f('ix_wx_versions_master_uid'), 'wx_versions', ['master_uid'], unique=False)
    op.add_column('wx_mini_apps', sa.Column('testers', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wx_mini_apps', 'testers')
    op.drop_index(op.f('ix_wx_versions_master_uid'), table_name='wx_versions')
    op.drop_index(op.f('ix_wx_versions_auth_app_id'), table_name='wx_versions')
    op.drop_table('wx_versions')
    # ### end Alembic commands ###
