"""add eorder to express

Revision ID: ffa9899bfd2c
Revises: c08f55b4a662
Create Date: 2017-09-26 12:12:59.475322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa9899bfd2c'
down_revision = 'c08f55b4a662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expresses', sa.Column('customer_name', sa.String(length=32), nullable=True))
    op.add_column('expresses', sa.Column('customer_pwd', sa.String(length=100), nullable=True))
    op.add_column('expresses', sa.Column('send_site', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expresses', 'send_site')
    op.drop_column('expresses', 'customer_pwd')
    op.drop_column('expresses', 'customer_name')
    # ### end Alembic commands ###
